import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget1/generated/GeneratedRectangle458Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget1/generated/GeneratedLine219Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget1/generated/GeneratedGroup22Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget1/generated/Generated232979Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget1/generated/GeneratedYourQueueNois007Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget1/generated/GeneratedQRcodeisnotfunctioningWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget1/generated/GeneratedYourorderwillbereadyin24minutesWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget1/generated/GeneratedUseReferenceCodeWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget1/generated/GeneratedGroup44Widget18.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget1/generated/GeneratedBxbxbookWidget21.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget1/generated/GeneratedGroup55Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget1/generated/GeneratedGroup84Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget1/generated/GeneratedClaritynotificationlineWidget21.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget1/generated/GeneratedYourReferenceQRCodeWidget1.dart';

/* Frame After Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAfterPaymentWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget21(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget21(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget10(),
              ),
              Positioned(
                left: -0.00048828125,
                top: 57.5,
                right: null,
                bottom: null,
                width: 414.001220703125,
                height: 1.0,
                child: GeneratedLine219Widget10(),
              ),
              Positioned(
                left: 109.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 19.0,
                child: GeneratedYourQueueNois007Widget4(),
              ),
              Positioned(
                left: 100.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 19.0,
                child: GeneratedYourReferenceQRCodeWidget1(),
              ),
              Positioned(
                left: 46.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 19.0,
                child: GeneratedYourorderwillbereadyin24minutesWidget1(),
              ),
              Positioned(
                left: 109.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 193.0,
                child: GeneratedRectangle458Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget18(),
              ),
              Positioned(
                left: 110.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 41.0,
                child: GeneratedGroup84Widget1(),
              ),
              Positioned(
                left: 121.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 15.0,
                child: GeneratedQRcodeisnotfunctioningWidget1(),
              ),
              Positioned(
                left: 116.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 19.0,
                child: GeneratedUseReferenceCodeWidget1(),
              ),
              Positioned(
                left: 175.0,
                top: 548.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 22.0,
                child: Generated232979Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup22Widget5(),
              )
            ]),
      ),
    ));
  }
}
