import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedRoyalRestaurantWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedRectangle5Widget74.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedClaritynotificationlineWidget35.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedEarliestavailablein80minWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedEarliestavailablein120minWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedFrame1Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedGroup42Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedGroup13Widget56.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedRectangle6Widget74.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedPlacesnearyouWidget9.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedGroup12Widget55.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedGroup3Widget12.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedGroup44Widget27.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedGroup43Widget15.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedEarliestavailablein60minWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedGroup41Widget30.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedGroup14Widget54.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedBxbxbookWidget35.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/Generated12Sec9ambalaHaryanaWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedrestaurantwidget1/generated/GeneratedGroup34Widget9.dart';

/* Frame Restaurant
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRestaurantWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(2.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 736.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 736.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(2.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(2.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 43.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 42.0,
                              child: GeneratedGroup3Widget12(),
                            ),
                            Positioned(
                              left: 5.0,
                              top: 6.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedClaritynotificationlineWidget35(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 11.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBxbxbookWidget35(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 96.0,
                              right: null,
                              bottom: null,
                              width: 407.0,
                              height: 69.0,
                              child: GeneratedFrame1Widget9(),
                            ),
                            Positioned(
                              left: 148.0,
                              top: 8.0,
                              right: null,
                              bottom: null,
                              width: 129.0,
                              height: 30.0,
                              child: GeneratedGroup42Widget1(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 86.0,
                              height: 12.0,
                              child: GeneratedPlacesnearyouWidget9(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 276.0,
                              right: null,
                              bottom: null,
                              width: 416.0,
                              height: 80.0,
                              child: GeneratedRectangle5Widget74(),
                            ),
                            Positioned(
                              left: 265.0,
                              top: 337.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 12.0,
                              child: GeneratedEarliestavailablein60minWidget1(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 284.0,
                              right: null,
                              bottom: null,
                              width: 95.0,
                              height: 13.0,
                              child: GeneratedRoyalRestaurantWidget1(),
                            ),
                            Positioned(
                              left: 91.0,
                              top: 299.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 11.0,
                              child: Generated12Sec9ambalaHaryanaWidget1(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 283.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 64.0,
                              child: GeneratedRectangle6Widget74(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 313.0,
                              right: null,
                              bottom: null,
                              width: 81.0,
                              height: 15.0,
                              child: GeneratedGroup12Widget55(),
                            ),
                            Positioned(
                              left: 209.0,
                              top: 313.0,
                              right: null,
                              bottom: null,
                              width: 27.0,
                              height: 15.0,
                              child: GeneratedGroup14Widget54(),
                            ),
                            Positioned(
                              left: 174.0,
                              top: 313.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 15.0,
                              child: GeneratedGroup13Widget56(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 434.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup43Widget15(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 197.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup41Widget30(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 355.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup44Widget27(),
                            ),
                            Positioned(
                              left: 264.0,
                              top: 417.0,
                              right: null,
                              bottom: null,
                              width: 146.0,
                              height: 12.0,
                              child: GeneratedEarliestavailablein80minWidget1(),
                            ),
                            Positioned(
                              left: 263.0,
                              top: 495.0,
                              right: null,
                              bottom: null,
                              width: 149.0,
                              height: 12.0,
                              child:
                                  GeneratedEarliestavailablein120minWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 686.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 50.0,
                              child: GeneratedGroup34Widget9(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
