import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/Generatedmax6peoplepertableWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedNoofpeopleWidget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup60Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup47Widget32.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup69Widget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedNooftablesWidget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup66Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedForprebookingyouneedtobookatleastadaybeforeWidget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedPricetableWidget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedYourBookingWidget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup59Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedSelectDateandTimeWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedClaritynotificationlineWidget12.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedClaritynotificationlineWidget11.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup21Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedLine216Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup44Widget14.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup56Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup68Widget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup63Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedLine220Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedBxbxbookWidget11.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedTableReservationWidget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup43Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup64Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup48Widget16.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedOtherchargesWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup57Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedQuantityWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedBxbxbookWidget12.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup46Widget31.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup58Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGrandTotalWidget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedTotalWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedTablesWidget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedTotaltablesWidget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/Generated50ofthismoneycanbereclaimedwhileorderingWidget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedGroup55Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget2/generated/GeneratedLine219Widget3.dart';

/* Frame Pre Order
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPreOrderWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget11(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget11(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup43Widget8(),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget12(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget12(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget3(),
              ),
              Positioned(
                left: 82.0,
                top: 515.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup59Widget3(),
              ),
              Positioned(
                left: 215.0,
                top: 515.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup60Widget3(),
              ),
              Positioned(
                left: 73.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 12.0,
                child:
                    GeneratedForprebookingyouneedtobookatleastadaybeforeWidget(),
              ),
              Positioned(
                left: 207.5,
                top: 546.0146484375,
                right: null,
                bottom: null,
                width: 34.01470184326172,
                height: 1.0,
                child: GeneratedLine220Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget14(),
              ),
              Positioned(
                left: 9.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 15.0,
                child: GeneratedSelectDateandTimeWidget2(),
              ),
              Positioned(
                left: 10.0,
                top: 604.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 24.0,
                child: GeneratedGroup63Widget2(),
              ),
              Positioned(
                left: 164.0,
                top: 604.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 24.0,
                child: GeneratedGroup64Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 46.0,
                child: GeneratedGroup66Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup21Widget1(),
              ),
              Positioned(
                left: 5.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 15.0,
                child: GeneratedYourBookingWidget(),
              ),
              Positioned(
                left: 133.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 18.0,
                child: GeneratedPricetableWidget(),
              ),
              Positioned(
                left: 255.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 18.0,
                child: GeneratedTotalWidget3(),
              ),
              Positioned(
                left: 336.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 18.0,
                child: GeneratedQuantityWidget3(),
              ),
              Positioned(
                left: 8.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 21.0,
                child: GeneratedTablesWidget(),
              ),
              Positioned(
                left: 9.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 18.0,
                child: GeneratedTotaltablesWidget(),
              ),
              Positioned(
                left: 9.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 18.0,
                child: GeneratedGrandTotalWidget7(),
              ),
              Positioned(
                left: 9.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 18.0,
                child: GeneratedOtherchargesWidget2(),
              ),
              Positioned(
                left: 332.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup47Widget32(),
              ),
              Positioned(
                left: 327.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup68Widget(),
              ),
              Positioned(
                left: 327.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup69Widget(),
              ),
              Positioned(
                left: 136.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup46Widget31(),
              ),
              Positioned(
                left: 243.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup48Widget16(),
              ),
              Positioned(
                left: 338.0,
                top: 369.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup56Widget3(),
              ),
              Positioned(
                left: 338.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup58Widget3(),
              ),
              Positioned(
                left: 338.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup57Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine216Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine219Widget3(),
              ),
              Positioned(
                left: 8.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 18.0,
                child: GeneratedTableReservationWidget(),
              ),
              Positioned(
                left: 8.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 16.0,
                child: GeneratedNoofpeopleWidget(),
              ),
              Positioned(
                left: 8.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 16.0,
                child: GeneratedNooftablesWidget(),
              ),
              Positioned(
                left: 8.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 12.0,
                child: Generatedmax6peoplepertableWidget1(),
              ),
              Positioned(
                left: 73.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 12.0,
                child:
                    Generated50ofthismoneycanbereclaimedwhileorderingWidget(),
              )
            ]),
      ),
    ));
  }
}
