import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget7/generated/GeneratedGroup79Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget7/generated/GeneratedGrandTotalWidget27.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget7/generated/GeneratedPaymentOptionsWidget8.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget7/generated/GeneratedGroup76Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget7/generated/GeneratedGroup22Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget7/generated/GeneratedYourorderwillbereadyin30minutesWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget7/generated/GeneratedLine219Widget25.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget7/generated/GeneratedClaritynotificationlineWidget45.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget7/generated/GeneratedYourQueueNois007Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget7/generated/GeneratedGroup55Widget25.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget7/generated/GeneratedGroup61Widget14.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget7/generated/GeneratedBxbxbookWidget45.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget7/generated/GeneratedGroup75Widget5.dart';

/* Frame After clicking book now
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAfterclickingbooknowWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget45(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget45(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget25(),
              ),
              Positioned(
                left: -0.00048828125,
                top: 57.5,
                right: null,
                bottom: null,
                width: 414.001220703125,
                height: 1.0,
                child: GeneratedLine219Widget25(),
              ),
              Positioned(
                left: 55.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 18.0,
                child: GeneratedYourorderwillbereadyin30minutesWidget3(),
              ),
              Positioned(
                left: 331.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 22.0,
                child: GeneratedGroup61Widget14(),
              ),
              Positioned(
                left: 8.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 19.0,
                child: GeneratedGrandTotalWidget27(),
              ),
              Positioned(
                left: 54.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 43.0,
                child: GeneratedGroup79Widget4(),
              ),
              Positioned(
                left: 6.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 31.0,
                child: GeneratedPaymentOptionsWidget8(),
              ),
              Positioned(
                left: 42.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 58.0,
                child: GeneratedGroup76Widget5(),
              ),
              Positioned(
                left: 42.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 58.0,
                child: GeneratedGroup75Widget5(),
              ),
              Positioned(
                left: 106.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 19.0,
                child: GeneratedYourQueueNois007Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup22Widget10(),
              )
            ]),
      ),
    ));
  }
}
