import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedsecondtimewidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/nowaytapp/generatedsecondtimewidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/nowaytapp/generatedsecondtimewidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/nowaytapp/generatedsecondtimewidget/generated/GeneratedCurrentLocationWidget.dart';

/* Frame Second Time
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSecondTimeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 86.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 245.0,
                height: 252.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 71.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 87.0,
                top: 339.0,
                right: null,
                bottom: null,
                width: 207.0,
                height: 34.0,
                child: GeneratedCurrentLocationWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 71.0,
                child: GeneratedGroup4Widget(),
              )
            ]),
      ),
    ));
  }
}
