import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGroup56Widget11.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedTableReservationWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/Generatedmax6peoplepertableWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedBxbxbookWidget50.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedTotalWidget11.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedPricetableWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGroup44Widget41.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedIfyoubooknowWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGroup67Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedLine216Widget11.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGroup48Widget37.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedTablesWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedYourBookingWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedNooftablesWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGrandTotalWidget31.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGroup68Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGroup47Widget69.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGroup59Widget11.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGroup58Widget14.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGroup55Widget29.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGroup60Widget11.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedQuantityWidget11.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedBxbxbookWidget51.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedOtherchargesWidget9.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedLine219Widget29.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGroup46Widget67.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedClaritynotificationlineWidget51.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGroup43Widget21.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedNoofpeopleWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/Generated70ofthismoneycanbereclaimedwhileorderingWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGroup69Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedClaritynotificationlineWidget50.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGroup21Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedGroup57Widget11.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedTotaltablesWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedYourQueueNowillbe007Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedLine220Widget11.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget16/generated/GeneratedYourreservationwillbeavailableinapproximately50minutesW1.dart';

/* Frame Book Now
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBookNowWidget16 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget50(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget50(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup43Widget21(),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget51(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget51(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget29(),
              ),
              Positioned(
                left: 5.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 15.0,
                child: GeneratedYourBookingWidget3(),
              ),
              Positioned(
                left: 133.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 18.0,
                child: GeneratedPricetableWidget3(),
              ),
              Positioned(
                left: 255.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 18.0,
                child: GeneratedTotalWidget11(),
              ),
              Positioned(
                left: 336.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 18.0,
                child: GeneratedQuantityWidget11(),
              ),
              Positioned(
                left: 8.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 21.0,
                child: GeneratedTablesWidget3(),
              ),
              Positioned(
                left: 9.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 18.0,
                child: GeneratedTotaltablesWidget3(),
              ),
              Positioned(
                left: 9.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 18.0,
                child: GeneratedGrandTotalWidget31(),
              ),
              Positioned(
                left: 9.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 18.0,
                child: GeneratedOtherchargesWidget9(),
              ),
              Positioned(
                left: 332.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup47Widget69(),
              ),
              Positioned(
                left: 327.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup68Widget8(),
              ),
              Positioned(
                left: 327.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup69Widget3(),
              ),
              Positioned(
                left: 136.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup46Widget67(),
              ),
              Positioned(
                left: 243.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup48Widget37(),
              ),
              Positioned(
                left: 338.0,
                top: 369.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup56Widget11(),
              ),
              Positioned(
                left: 338.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup58Widget14(),
              ),
              Positioned(
                left: 338.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup57Widget11(),
              ),
              Positioned(
                left: 0.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine216Widget11(),
              ),
              Positioned(
                left: 0.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine219Widget29(),
              ),
              Positioned(
                left: 82.0,
                top: 474.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup59Widget11(),
              ),
              Positioned(
                left: 215.0,
                top: 474.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup60Widget11(),
              ),
              Positioned(
                left: 50.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 12.0,
                child:
                    GeneratedYourreservationwillbeavailableinapproximately50minutesW1(),
              ),
              Positioned(
                left: 7.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 19.0,
                child: GeneratedIfyoubooknowWidget5(),
              ),
              Positioned(
                left: 207.5,
                top: 505.0146484375,
                right: null,
                bottom: null,
                width: 34.01470184326172,
                height: 1.0,
                child: GeneratedLine220Widget11(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget41(),
              ),
              Positioned(
                left: 0.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 46.0,
                child: GeneratedGroup67Widget10(),
              ),
              Positioned(
                left: 100.0,
                top: 553.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 18.0,
                child: GeneratedYourQueueNowillbe007Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup21Widget10(),
              ),
              Positioned(
                left: 8.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 18.0,
                child: GeneratedTableReservationWidget3(),
              ),
              Positioned(
                left: 8.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 16.0,
                child: GeneratedNoofpeopleWidget3(),
              ),
              Positioned(
                left: 8.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 16.0,
                child: GeneratedNooftablesWidget3(),
              ),
              Positioned(
                left: 8.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 12.0,
                child: Generatedmax6peoplepertableWidget5(),
              ),
              Positioned(
                left: 73.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 12.0,
                child:
                    Generated70ofthismoneycanbereclaimedwhileorderingWidget1(),
              )
            ]),
      ),
    ));
  }
}
