import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget/generated/GeneratedPaymentOptionsWidget6.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget/generated/GeneratedLine219Widget19.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget/generated/GeneratedGroup76Widget3.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget/generated/GeneratedGroup77Widget.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget/generated/GeneratedGroup74Widget.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget/generated/GeneratedBxbxbookWidget30.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget/generated/GeneratedGroup75Widget3.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget/generated/GeneratedClaritynotificationlineWidget30.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget/generated/GeneratedGroup55Widget19.dart';

/* Frame iPhone 8 Plus - 14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone8Plus14Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget30(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget30(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget19(),
              ),
              Positioned(
                left: -0.00048828125,
                top: 57.5,
                right: null,
                bottom: null,
                width: 414.001220703125,
                height: 1.0,
                child: GeneratedLine219Widget19(),
              ),
              Positioned(
                left: 116.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 31.0,
                child: GeneratedPaymentOptionsWidget6(),
              ),
              Positioned(
                left: 42.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 71.0,
                child: GeneratedGroup76Widget3(),
              ),
              Positioned(
                left: 42.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 71.0,
                child: GeneratedGroup75Widget3(),
              ),
              Positioned(
                left: 42.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 71.0,
                child: GeneratedGroup74Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 71.0,
                child: GeneratedGroup77Widget(),
              )
            ]),
      ),
    ));
  }
}
