description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "PT Serif Caption"
      fonts: 
        - 
          asset: "fonts/PTSerifCaption-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Cabin"
      fonts: 
        - 
          asset: "fonts/Cabin-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Cabin-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Cabin-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Cabin-500.ttf"
          style: "normal"
          weight: 500
    - 
      family: "Roboto"
      fonts: 
        - 
          asset: "fonts/Roboto-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Rosario"
      fonts: 
        - 
          asset: "fonts/Rosario-700.ttf"
          style: "normal"
          weight: 700
  uses-material-design: true
