import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget2/generated/Generated232979Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget2/generated/GeneratedRectangle458Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget2/generated/GeneratedYourQueueNois007Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget2/generated/GeneratedQRcodeisnotfunctioningWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget2/generated/GeneratedYourreservationwillbereadyin49minutesWidget.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget2/generated/GeneratedGroup21Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget2/generated/GeneratedYourReferenceQRCodeWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget2/generated/GeneratedLine219Widget11.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget2/generated/GeneratedUseReferenceCodeWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget2/generated/GeneratedGroup55Widget11.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget2/generated/GeneratedClaritynotificationlineWidget22.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget2/generated/GeneratedBxbxbookWidget22.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget2/generated/GeneratedGroup44Widget19.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget2/generated/GeneratedYourreservationwillbeexpireafter10minutesfromdesignated.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget2/generated/GeneratedGroup84Widget2.dart';

/* Frame After Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAfterPaymentWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget22(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget22(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget11(),
              ),
              Positioned(
                left: -0.00048828125,
                top: 57.5,
                right: null,
                bottom: null,
                width: 414.001220703125,
                height: 1.0,
                child: GeneratedLine219Widget11(),
              ),
              Positioned(
                left: 109.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 19.0,
                child: GeneratedYourQueueNois007Widget5(),
              ),
              Positioned(
                left: 100.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 19.0,
                child: GeneratedYourReferenceQRCodeWidget2(),
              ),
              Positioned(
                left: 21.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 19.0,
                child: GeneratedYourreservationwillbereadyin49minutesWidget(),
              ),
              Positioned(
                left: 109.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 193.0,
                child: GeneratedRectangle458Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget19(),
              ),
              Positioned(
                left: 110.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 41.0,
                child: GeneratedGroup84Widget2(),
              ),
              Positioned(
                left: 121.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 15.0,
                child: GeneratedQRcodeisnotfunctioningWidget2(),
              ),
              Positioned(
                left: 116.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 19.0,
                child: GeneratedUseReferenceCodeWidget2(),
              ),
              Positioned(
                left: 175.0,
                top: 548.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 22.0,
                child: Generated232979Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup21Widget4(),
              ),
              Positioned(
                left: 30.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 12.0,
                child:
                    GeneratedYourreservationwillbeexpireafter10minutesfromdesignated(),
              )
            ]),
      ),
    ));
  }
}
