import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedRectangle426Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedCVVnoWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedTopBarWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedGroup68Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedCardNumberWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedRectangle423Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedNameoncardWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedGroup70Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedBottombarbalancedWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedExpirydateWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedRectangle428Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedContinueWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedRectangle427Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedGroup3Widget13.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedGroup67Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedRectangle425Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedRectangle424Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedandroid47widget1/generated/GeneratedGroup71Widget1.dart';

/* Frame Android - 47
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid47Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 780.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 14.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 329.0,
                child: GeneratedRectangle423Widget1(),
              ),
              Positioned(
                left: 18.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 71.0,
                child: GeneratedGroup67Widget8(),
              ),
              Positioned(
                left: 16.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 71.0,
                child: GeneratedGroup68Widget7(),
              ),
              Positioned(
                left: 17.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 71.0,
                child: GeneratedGroup70Widget1(),
              ),
              Positioned(
                left: 308.0,
                top: 182.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedGroup3Widget13(),
              ),
              Positioned(
                left: 30.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 23.0,
                child: GeneratedNameoncardWidget1(),
              ),
              Positioned(
                left: 32.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 23.0,
                child: GeneratedCardNumberWidget1(),
              ),
              Positioned(
                left: 48.0,
                top: 347.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 23.0,
                child: GeneratedExpirydateWidget1(),
              ),
              Positioned(
                left: 76.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 23.0,
                child: GeneratedCVVnoWidget1(),
              ),
              Positioned(
                left: 203.0,
                top: 438.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 37.0,
                child: GeneratedRectangle424Widget1(),
              ),
              Positioned(
                left: 231.0,
                top: 444.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: GeneratedContinueWidget1(),
              ),
              Positioned(
                left: 150.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 23.0,
                child: GeneratedRectangle425Widget1(),
              ),
              Positioned(
                left: 150.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 23.0,
                child: GeneratedRectangle426Widget1(),
              ),
              Positioned(
                left: 150.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 23.0,
                child: GeneratedRectangle427Widget1(),
              ),
              Positioned(
                left: 150.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 23.0,
                child: GeneratedRectangle428Widget1(),
              ),
              Positioned(
                left: 18.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 71.0,
                child: GeneratedGroup71Widget1(),
              ),
              Positioned(
                left: -17.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 28.0,
                child: GeneratedTopBarWidget1(),
              ),
              Positioned(
                left: -13.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 30.0,
                child: GeneratedBottombarbalancedWidget1(),
              )
            ]),
      ),
    ));
  }
}
