import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedLine217Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup22Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup55Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup67Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedLine219Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedQuantityWidget4.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup58Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedIfyoubooknowWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedYourQueueNowillbe007Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedTotalWidget4.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup48Widget17.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup59Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedClaritynotificationlineWidget18.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup47Widget33.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup56Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedLine220Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup51Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedCoffeeWidget15.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedLine216Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedYourorderwillbereadyinapproximately30minutesWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGrandTotalWidget11.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedOtherchargesWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedBxbxbookWidget18.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedBxbxbookWidget17.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedYourOrderWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup49Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedBiscuitsPacketWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup43Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup60Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedPriceItemWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup46Widget32.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup44Widget16.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedClaritynotificationlineWidget17.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedItemTotalWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup50Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget5/generated/GeneratedGroup57Widget4.dart';

/* Frame Book Now
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBookNowWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget17(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget17(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup43Widget9(),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget18(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget18(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget8(),
              ),
              Positioned(
                left: 6.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 14.0,
                child: GeneratedYourOrderWidget3(),
              ),
              Positioned(
                left: 135.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 17.0,
                child: GeneratedPriceItemWidget3(),
              ),
              Positioned(
                left: 252.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 17.0,
                child: GeneratedTotalWidget4(),
              ),
              Positioned(
                left: 337.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 17.0,
                child: GeneratedQuantityWidget4(),
              ),
              Positioned(
                left: 7.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 21.0,
                child: GeneratedCoffeeWidget15(),
              ),
              Positioned(
                left: 7.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 18.0,
                child: GeneratedBiscuitsPacketWidget3(),
              ),
              Positioned(
                left: 9.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 18.0,
                child: GeneratedItemTotalWidget3(),
              ),
              Positioned(
                left: 9.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 18.0,
                child: GeneratedGrandTotalWidget11(),
              ),
              Positioned(
                left: 9.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 18.0,
                child: GeneratedOtherchargesWidget3(),
              ),
              Positioned(
                left: 332.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup47Widget33(),
              ),
              Positioned(
                left: 332.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup49Widget9(),
              ),
              Positioned(
                left: 136.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup46Widget32(),
              ),
              Positioned(
                left: 136.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 19.0,
                child: GeneratedGroup50Widget9(),
              ),
              Positioned(
                left: 243.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup48Widget17(),
              ),
              Positioned(
                left: 243.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup51Widget9(),
              ),
              Positioned(
                left: 338.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup56Widget4(),
              ),
              Positioned(
                left: 338.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup58Widget4(),
              ),
              Positioned(
                left: 338.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup57Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine216Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine217Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine219Widget8(),
              ),
              Positioned(
                left: 82.0,
                top: 370.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup59Widget4(),
              ),
              Positioned(
                left: 215.0,
                top: 370.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup60Widget4(),
              ),
              Positioned(
                left: 73.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 269.0,
                height: 12.0,
                child:
                    GeneratedYourorderwillbereadyinapproximately30minutesWidget1(),
              ),
              Positioned(
                left: 7.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 19.0,
                child: GeneratedIfyoubooknowWidget1(),
              ),
              Positioned(
                left: 207.5,
                top: 401.0146484375,
                right: null,
                bottom: null,
                width: 34.01470184326172,
                height: 1.0,
                child: GeneratedLine220Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget16(),
              ),
              Positioned(
                left: 0.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 46.0,
                child: GeneratedGroup67Widget2(),
              ),
              Positioned(
                left: 100.0,
                top: 449.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 18.0,
                child: GeneratedYourQueueNowillbe007Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup22Widget4(),
              )
            ]),
      ),
    ));
  }
}
