import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedBxbxbookWidget9.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup57Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup43Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup56Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup64Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedPriceItemWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup63Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup60Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup50Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedLine216Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup55Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup51Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedLine217Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedBiscuitsPacketWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedOtherchargesWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup46Widget30.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup44Widget13.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedBxbxbookWidget10.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedItemTotalWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedLine219Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedQuantityWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup47Widget31.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedLine220Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup66Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedClaritynotificationlineWidget9.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup58Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedTotalWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup49Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup59Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedSelectDateandTimeWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedForprebookingyouneedtobookatleastan1hourbeforethepickup1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup48Widget15.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedCoffeeWidget14.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGroup22Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedYourOrderWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedGrandTotalWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget1/generated/GeneratedClaritynotificationlineWidget10.dart';

/* Frame Pre Order
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPreOrderWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget9(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget9(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup43Widget7(),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget10(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget10(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget2(),
              ),
              Positioned(
                left: 6.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 14.0,
                child: GeneratedYourOrderWidget2(),
              ),
              Positioned(
                left: 135.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 17.0,
                child: GeneratedPriceItemWidget2(),
              ),
              Positioned(
                left: 252.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 17.0,
                child: GeneratedTotalWidget2(),
              ),
              Positioned(
                left: 337.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 17.0,
                child: GeneratedQuantityWidget2(),
              ),
              Positioned(
                left: 82.0,
                top: 375.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup59Widget2(),
              ),
              Positioned(
                left: 215.0,
                top: 375.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup60Widget2(),
              ),
              Positioned(
                left: 22.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 12.0,
                child:
                    GeneratedForprebookingyouneedtobookatleastan1hourbeforethepickup1(),
              ),
              Positioned(
                left: 207.5,
                top: 406.01470947265625,
                right: null,
                bottom: null,
                width: 34.01470184326172,
                height: 1.0,
                child: GeneratedLine220Widget2(),
              ),
              Positioned(
                left: -8.0,
                top: 1019.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget13(),
              ),
              Positioned(
                left: 9.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 15.0,
                child: GeneratedSelectDateandTimeWidget1(),
              ),
              Positioned(
                left: 10.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 24.0,
                child: GeneratedGroup63Widget1(),
              ),
              Positioned(
                left: 164.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 24.0,
                child: GeneratedGroup64Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 46.0,
                child: GeneratedGroup66Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup22Widget2(),
              ),
              Positioned(
                left: 7.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 21.0,
                child: GeneratedCoffeeWidget14(),
              ),
              Positioned(
                left: 7.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 18.0,
                child: GeneratedBiscuitsPacketWidget2(),
              ),
              Positioned(
                left: 9.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 18.0,
                child: GeneratedItemTotalWidget2(),
              ),
              Positioned(
                left: 9.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 18.0,
                child: GeneratedGrandTotalWidget5(),
              ),
              Positioned(
                left: 9.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 18.0,
                child: GeneratedOtherchargesWidget1(),
              ),
              Positioned(
                left: 332.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup47Widget31(),
              ),
              Positioned(
                left: 332.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup49Widget8(),
              ),
              Positioned(
                left: 136.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup46Widget30(),
              ),
              Positioned(
                left: 136.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 19.0,
                child: GeneratedGroup50Widget8(),
              ),
              Positioned(
                left: 243.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup48Widget15(),
              ),
              Positioned(
                left: 243.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup51Widget8(),
              ),
              Positioned(
                left: 338.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup56Widget2(),
              ),
              Positioned(
                left: 338.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup58Widget2(),
              ),
              Positioned(
                left: 338.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup57Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine216Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine217Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine219Widget2(),
              )
            ]),
      ),
    ));
  }
}
