import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedYourorderwillbereadyinapproximately30minutesWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup44Widget40.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedClaritynotificationlineWidget48.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup22Widget11.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup67Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedPriceItemWidget7.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedItemTotalWidget7.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedOtherchargesWidget8.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup46Widget66.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedBxbxbookWidget48.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup56Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup50Widget19.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup49Widget19.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup48Widget36.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedClaritynotificationlineWidget49.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedBiscuitsPacketWidget7.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup55Widget28.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup60Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup47Widget68.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup57Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup43Widget20.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup51Widget19.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedLine220Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedTotalWidget10.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedYourQueueNowillbe007Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup59Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGroup58Widget13.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedLine219Widget28.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedGrandTotalWidget29.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedLine217Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedBxbxbookWidget49.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedIfyoubooknowWidget4.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedLine216Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedYourOrderWidget7.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedQuantityWidget10.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget14/generated/GeneratedCoffeeWidget31.dart';

/* Frame Book Now
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBookNowWidget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget48(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget48(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup43Widget20(),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget49(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget49(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget28(),
              ),
              Positioned(
                left: 6.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 14.0,
                child: GeneratedYourOrderWidget7(),
              ),
              Positioned(
                left: 135.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 17.0,
                child: GeneratedPriceItemWidget7(),
              ),
              Positioned(
                left: 252.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 17.0,
                child: GeneratedTotalWidget10(),
              ),
              Positioned(
                left: 337.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 17.0,
                child: GeneratedQuantityWidget10(),
              ),
              Positioned(
                left: 7.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 21.0,
                child: GeneratedCoffeeWidget31(),
              ),
              Positioned(
                left: 7.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 18.0,
                child: GeneratedBiscuitsPacketWidget7(),
              ),
              Positioned(
                left: 9.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 18.0,
                child: GeneratedItemTotalWidget7(),
              ),
              Positioned(
                left: 9.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 18.0,
                child: GeneratedGrandTotalWidget29(),
              ),
              Positioned(
                left: 9.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 18.0,
                child: GeneratedOtherchargesWidget8(),
              ),
              Positioned(
                left: 332.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup47Widget68(),
              ),
              Positioned(
                left: 332.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup49Widget19(),
              ),
              Positioned(
                left: 136.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup46Widget66(),
              ),
              Positioned(
                left: 136.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 19.0,
                child: GeneratedGroup50Widget19(),
              ),
              Positioned(
                left: 243.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup48Widget36(),
              ),
              Positioned(
                left: 243.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup51Widget19(),
              ),
              Positioned(
                left: 338.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup56Widget10(),
              ),
              Positioned(
                left: 338.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup58Widget13(),
              ),
              Positioned(
                left: 338.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup57Widget10(),
              ),
              Positioned(
                left: 0.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine216Widget10(),
              ),
              Positioned(
                left: 0.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine217Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine219Widget28(),
              ),
              Positioned(
                left: 82.0,
                top: 370.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup59Widget10(),
              ),
              Positioned(
                left: 215.0,
                top: 370.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup60Widget10(),
              ),
              Positioned(
                left: 73.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 269.0,
                height: 12.0,
                child:
                    GeneratedYourorderwillbereadyinapproximately30minutesWidget3(),
              ),
              Positioned(
                left: 7.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 19.0,
                child: GeneratedIfyoubooknowWidget4(),
              ),
              Positioned(
                left: 207.5,
                top: 401.0146484375,
                right: null,
                bottom: null,
                width: 34.01470184326172,
                height: 1.0,
                child: GeneratedLine220Widget10(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget40(),
              ),
              Positioned(
                left: 0.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 46.0,
                child: GeneratedGroup67Widget9(),
              ),
              Positioned(
                left: 100.0,
                top: 449.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 18.0,
                child: GeneratedYourQueueNowillbe007Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup22Widget11(),
              )
            ]),
      ),
    ));
  }
}
