import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedSIGNINWITHWidget6.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedRectangle1Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedRectangle7Widget128.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedORWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedRectangle11Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedForgotthepasswordWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedSIGNINWITHWidget8.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedRectangle10Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedEnterPasswordWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedSIGNINWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedSIGNINWITHWidget7.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedRectangle8Widget17.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedDonthaveanaccountyetSignUpWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedEnterEmailPhonenumberWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedRectangle5Widget35.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedRectangle6Widget35.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget1/generated/GeneratedSIGNINWITHWidget5.dart';

/* Frame First Time
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFirstTimeWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 84.0,
                top: -19.0,
                right: null,
                bottom: null,
                width: 245.0,
                height: 252.0,
                child: GeneratedRectangle1Widget8(),
              ),
              Positioned(
                left: 70.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 38.0,
                child: GeneratedEnterEmailPhonenumberWidget2(),
              ),
              Positioned(
                left: 131.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 38.0,
                child: GeneratedEnterPasswordWidget2(),
              ),
              Positioned(
                left: 74.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 38.0,
                child: GeneratedRectangle5Widget35(),
              ),
              Positioned(
                left: 74.0,
                top: 356.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 38.0,
                child: GeneratedRectangle6Widget35(),
              ),
              Positioned(
                left: 133.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 21.0,
                child: GeneratedForgotthepasswordWidget1(),
              ),
              Positioned(
                left: 140.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 35.0,
                child: GeneratedRectangle7Widget128(),
              ),
              Positioned(
                left: 211.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 34.0,
                child: GeneratedRectangle8Widget17(),
              ),
              Positioned(
                left: 119.0,
                top: 553.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 34.0,
                child: GeneratedSIGNINWITHWidget5(),
              ),
              Positioned(
                left: 119.0,
                top: 553.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 34.0,
                child: GeneratedSIGNINWITHWidget6(),
              ),
              Positioned(
                left: 119.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 34.0,
                child: GeneratedSIGNINWITHWidget7(),
              ),
              Positioned(
                left: 119.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 34.0,
                child: GeneratedSIGNINWITHWidget8(),
              ),
              Positioned(
                left: 187.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 41.0,
                child: GeneratedORWidget2(),
              ),
              Positioned(
                left: 37.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 72.0,
                child: GeneratedDonthaveanaccountyetSignUpWidget1(),
              ),
              Positioned(
                left: 141.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 43.0,
                child: GeneratedRectangle9Widget1(),
              ),
              Positioned(
                left: 156.0,
                top: 458.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 34.0,
                child: GeneratedSIGNINWidget1(),
              ),
              Positioned(
                left: 143.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 49.0,
                child: GeneratedRectangle10Widget9(),
              ),
              Positioned(
                left: 222.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 49.0,
                child: GeneratedRectangle11Widget2(),
              )
            ]),
      ),
    ));
  }
}
