import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedmedicalwidget1/generated/GeneratedGroup44Widget25.dart';
import 'package:flutterapp/nowaytapp/generatedmedicalwidget1/generated/GeneratedGroup17Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedmedicalwidget1/generated/GeneratedGroup34Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedmedicalwidget1/generated/GeneratedGroup45Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedmedicalwidget1/generated/GeneratedGroup3Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedmedicalwidget1/generated/GeneratedBxbxbookWidget33.dart';
import 'package:flutterapp/nowaytapp/generatedmedicalwidget1/generated/GeneratedGroup43Widget13.dart';
import 'package:flutterapp/nowaytapp/generatedmedicalwidget1/generated/GeneratedClaritynotificationlineWidget33.dart';
import 'package:flutterapp/nowaytapp/generatedmedicalwidget1/generated/GeneratedFrame1Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedmedicalwidget1/generated/GeneratedPlacesnearyouWidget7.dart';
import 'package:flutterapp/nowaytapp/generatedmedicalwidget1/generated/GeneratedGroup18Widget1.dart';

/* Frame Medical
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMedicalWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(2.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 736.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 736.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(2.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(2.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 43.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 42.0,
                              child: GeneratedGroup3Widget10(),
                            ),
                            Positioned(
                              left: 5.0,
                              top: 6.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedClaritynotificationlineWidget33(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 11.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBxbxbookWidget33(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 96.0,
                              right: null,
                              bottom: null,
                              width: 407.0,
                              height: 69.0,
                              child: GeneratedFrame1Widget7(),
                            ),
                            Positioned(
                              left: 148.0,
                              top: 8.0,
                              right: null,
                              bottom: null,
                              width: 129.0,
                              height: 30.0,
                              child: GeneratedGroup43Widget13(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 86.0,
                              height: 12.0,
                              child: GeneratedPlacesnearyouWidget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 195.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup17Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 352.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup44Widget25(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 274.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup18Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 431.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup45Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 686.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 50.0,
                              child: GeneratedGroup34Widget7(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
