import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedgroup3widget14/generated/GeneratedRectangle1Widget17.dart';
import 'package:flutterapp/nowaytapp/generatedgroup3widget14/generated/GeneratedGroup1Widget12.dart';

/* Group Group 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup3Widget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 414.0,
      height: 42.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 42.0,
              child: GeneratedRectangle1Widget17(),
            ),
            Positioned(
              left: 7.0,
              top: 5.0,
              right: null,
              bottom: null,
              width: 397.0,
              height: 32.0,
              child: GeneratedGroup1Widget12(),
            )
          ]),
    ));
  }
}
