import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget3/generated/GeneratedGroup78Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget3/generated/GeneratedBxbxbookWidget27.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget3/generated/GeneratedGroup80Widget.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget3/generated/GeneratedGroup67Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget3/generated/GeneratedGroup58Widget6.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget3/generated/GeneratedGroup55Widget16.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget3/generated/GeneratedPaymentOptionsWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget3/generated/GeneratedGrandTotalWidget15.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget3/generated/GeneratedLine219Widget16.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget3/generated/GeneratedGroup68Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget3/generated/GeneratedClaritynotificationlineWidget27.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget3/generated/GeneratedSelectedDateandTimeWidget.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget3/generated/GeneratedGroup78Widget.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget3/generated/GeneratedEstimatedTime2days4hrs30minsWidget6.dart';

/* Frame After clicking book now
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAfterclickingbooknowWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget27(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget27(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget16(),
              ),
              Positioned(
                left: -0.00048828125,
                top: 57.5,
                right: null,
                bottom: null,
                width: 414.001220703125,
                height: 1.0,
                child: GeneratedLine219Widget16(),
              ),
              Positioned(
                left: 54.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 43.0,
                child: GeneratedGroup78Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 31.0,
                child: GeneratedPaymentOptionsWidget3(),
              ),
              Positioned(
                left: 42.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 58.0,
                child: GeneratedGroup80Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 58.0,
                child: GeneratedGroup78Widget1(),
              ),
              Positioned(
                left: 15.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 21.0,
                child: GeneratedGrandTotalWidget15(),
              ),
              Positioned(
                left: 339.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup58Widget6(),
              ),
              Positioned(
                left: 15.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 207.0,
                height: 19.0,
                child: GeneratedSelectedDateandTimeWidget(),
              ),
              Positioned(
                left: 242.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 24.0,
                child: GeneratedGroup68Widget3(),
              ),
              Positioned(
                left: 70.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 18.0,
                child: GeneratedEstimatedTime2days4hrs30minsWidget6(),
              ),
              Positioned(
                left: 77.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 24.0,
                child: GeneratedGroup67Widget4(),
              )
            ]),
      ),
    ));
  }
}
