import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus9widget1/generated/GeneratedGroup48Widget22.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus9widget1/generated/GeneratedGroup51Widget12.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus9widget1/generated/GeneratedRectangle10Widget14.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus9widget1/generated/GeneratedServicesProvidedWidget10.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus9widget1/generated/GeneratedGroup44Widget31.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus9widget1/generated/Generated12Sec9ambalaHaryana7206899009Widget7.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus9widget1/generated/GeneratedBxbxarrowbackWidget10.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus9widget1/generated/GeneratedSardhadiagnosticWidget8.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus9widget1/generated/GeneratedGroup49Widget12.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus9widget1/generated/GeneratedGroup50Widget12.dart';

/* Frame iPhone 8 Plus - 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone8Plus9Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 195.0,
                child: GeneratedRectangle10Widget14(),
              ),
              Positioned(
                left: 10.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 12.0,
                child: Generated12Sec9ambalaHaryana7206899009Widget7(),
              ),
              Positioned(
                left: 2.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget10(),
              ),
              Positioned(
                left: 8.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 239.0,
                height: 29.0,
                child: GeneratedSardhadiagnosticWidget8(),
              ),
              Positioned(
                left: 7.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 15.0,
                child: GeneratedServicesProvidedWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget31(),
              ),
              Positioned(
                left: 12.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup48Widget22(),
              ),
              Positioned(
                left: 12.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup49Widget12(),
              ),
              Positioned(
                left: 12.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup50Widget12(),
              ),
              Positioned(
                left: 12.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup51Widget12(),
              )
            ]),
      ),
    ));
  }
}
