import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/GeneratedQRcodeisnotfunctioningWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/GeneratedClaritynotificationlineWidget25.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/GeneratedRectangle458Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/GeneratedDateandTimeWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/GeneratedEstimatedTime2days4hrs30minsWidget4.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/GeneratedGroup82Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/Generated232979Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/GeneratedGroup81Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/GeneratedUseReferenceCodeWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/GeneratedYourReferenceQRCodeWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/GeneratedLine219Widget14.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/GeneratedGroup83Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/GeneratedGroup55Widget14.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/GeneratedGroup44Widget22.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/GeneratedBxbxbookWidget25.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget5/generated/GeneratedGroup22Widget6.dart';

/* Frame After Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAfterPaymentWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget25(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget25(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget14(),
              ),
              Positioned(
                left: -0.00048828125,
                top: 57.5,
                right: null,
                bottom: null,
                width: 414.001220703125,
                height: 1.0,
                child: GeneratedLine219Widget14(),
              ),
              Positioned(
                left: 103.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 19.0,
                child: GeneratedYourReferenceQRCodeWidget5(),
              ),
              Positioned(
                left: 137.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 19.0,
                child: GeneratedDateandTimeWidget1(),
              ),
              Positioned(
                left: 247.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 24.0,
                child: GeneratedGroup81Widget1(),
              ),
              Positioned(
                left: 63.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 18.0,
                child: GeneratedEstimatedTime2days4hrs30minsWidget4(),
              ),
              Positioned(
                left: 37.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 24.0,
                child: GeneratedGroup82Widget1(),
              ),
              Positioned(
                left: 111.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 193.0,
                child: GeneratedRectangle458Widget5(),
              ),
              Positioned(
                left: -8.0,
                top: 1019.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget22(),
              ),
              Positioned(
                left: 110.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 41.0,
                child: GeneratedGroup83Widget1(),
              ),
              Positioned(
                left: 122.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 15.0,
                child: GeneratedQRcodeisnotfunctioningWidget5(),
              ),
              Positioned(
                left: 117.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 19.0,
                child: GeneratedUseReferenceCodeWidget5(),
              ),
              Positioned(
                left: 176.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 22.0,
                child: Generated232979Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup22Widget6(),
              )
            ]),
      ),
    ));
  }
}
