import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedBxbxbookWidget19.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedLine219Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedTablesWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGroup43Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedBxbxbookWidget20.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedLine220Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGroup69Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedClaritynotificationlineWidget20.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/Generated70ofthismoneycanbereclaimedwhileorderingWidget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedOtherchargesWidget4.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedIfyoubooknowWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGroup58Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGrandTotalWidget13.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedYourQueueNowillbe007Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGroup68Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGroup56Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/Generatedmax6peoplepertableWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedClaritynotificationlineWidget19.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGroup48Widget18.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGroup55Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedTotalWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedYourBookingWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGroup46Widget33.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedPricetableWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedNoofpeopleWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGroup44Widget17.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGroup60Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedLine216Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGroup21Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedQuantityWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGroup67Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedNooftablesWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGroup59Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedTableReservationWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedTotaltablesWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGroup57Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedYourreservationwillbeavailableinapproximately50minutesW.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget7/generated/GeneratedGroup47Widget34.dart';

/* Frame Book Now
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBookNowWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget19(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget19(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup43Widget10(),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget20(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget20(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget9(),
              ),
              Positioned(
                left: 5.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 15.0,
                child: GeneratedYourBookingWidget1(),
              ),
              Positioned(
                left: 133.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 18.0,
                child: GeneratedPricetableWidget1(),
              ),
              Positioned(
                left: 255.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 18.0,
                child: GeneratedTotalWidget5(),
              ),
              Positioned(
                left: 336.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 18.0,
                child: GeneratedQuantityWidget5(),
              ),
              Positioned(
                left: 8.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 21.0,
                child: GeneratedTablesWidget1(),
              ),
              Positioned(
                left: 9.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 18.0,
                child: GeneratedTotaltablesWidget1(),
              ),
              Positioned(
                left: 9.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 18.0,
                child: GeneratedGrandTotalWidget13(),
              ),
              Positioned(
                left: 9.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 18.0,
                child: GeneratedOtherchargesWidget4(),
              ),
              Positioned(
                left: 332.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup47Widget34(),
              ),
              Positioned(
                left: 327.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup68Widget2(),
              ),
              Positioned(
                left: 327.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup69Widget1(),
              ),
              Positioned(
                left: 136.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup46Widget33(),
              ),
              Positioned(
                left: 243.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup48Widget18(),
              ),
              Positioned(
                left: 338.0,
                top: 369.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup56Widget5(),
              ),
              Positioned(
                left: 338.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup58Widget5(),
              ),
              Positioned(
                left: 338.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup57Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine216Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine219Widget9(),
              ),
              Positioned(
                left: 82.0,
                top: 474.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup59Widget5(),
              ),
              Positioned(
                left: 215.0,
                top: 474.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup60Widget5(),
              ),
              Positioned(
                left: 50.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 12.0,
                child:
                    GeneratedYourreservationwillbeavailableinapproximately50minutesW(),
              ),
              Positioned(
                left: 7.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 19.0,
                child: GeneratedIfyoubooknowWidget2(),
              ),
              Positioned(
                left: 207.5,
                top: 505.0146484375,
                right: null,
                bottom: null,
                width: 34.01470184326172,
                height: 1.0,
                child: GeneratedLine220Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget17(),
              ),
              Positioned(
                left: 0.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 46.0,
                child: GeneratedGroup67Widget3(),
              ),
              Positioned(
                left: 100.0,
                top: 553.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 18.0,
                child: GeneratedYourQueueNowillbe007Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup21Widget3(),
              ),
              Positioned(
                left: 8.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 18.0,
                child: GeneratedTableReservationWidget1(),
              ),
              Positioned(
                left: 8.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 16.0,
                child: GeneratedNoofpeopleWidget1(),
              ),
              Positioned(
                left: 8.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 16.0,
                child: GeneratedNooftablesWidget1(),
              ),
              Positioned(
                left: 8.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 12.0,
                child: Generatedmax6peoplepertableWidget2(),
              ),
              Positioned(
                left: 73.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 12.0,
                child:
                    Generated70ofthismoneycanbereclaimedwhileorderingWidget(),
              )
            ]),
      ),
    ));
  }
}
