import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup21Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedYourBookingWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedTablesWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedTableReservationWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup48Widget35.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup58Widget12.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedQuantityWidget9.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup68Widget6.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup56Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedPricetableWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedOtherchargesWidget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/Generatedmax6peoplepertableWidget4.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedClaritynotificationlineWidget42.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup63Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedSelectDateandTimeWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedBxbxbookWidget42.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedLine219Widget23.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedBxbxbookWidget43.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup46Widget65.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup55Widget23.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedNooftablesWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup69Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedLine216Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup59Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup44Widget38.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup60Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup47Widget67.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedTotaltablesWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup43Widget19.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedNoofpeopleWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedLine220Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGrandTotalWidget25.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedForprebookingyouneedtobookatleastadaybeforeWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup64Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/Generated50ofthismoneycanbereclaimedwhileorderingWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedTotalWidget9.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup57Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedClaritynotificationlineWidget43.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget5/generated/GeneratedGroup66Widget5.dart';

/* Frame Pre Order
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPreOrderWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget42(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget42(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup43Widget19(),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget43(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget43(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget23(),
              ),
              Positioned(
                left: 82.0,
                top: 515.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup59Widget9(),
              ),
              Positioned(
                left: 215.0,
                top: 515.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup60Widget9(),
              ),
              Positioned(
                left: 73.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 12.0,
                child:
                    GeneratedForprebookingyouneedtobookatleastadaybeforeWidget1(),
              ),
              Positioned(
                left: 207.5,
                top: 546.0146484375,
                right: null,
                bottom: null,
                width: 34.01470184326172,
                height: 1.0,
                child: GeneratedLine220Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget38(),
              ),
              Positioned(
                left: 9.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 15.0,
                child: GeneratedSelectDateandTimeWidget5(),
              ),
              Positioned(
                left: 10.0,
                top: 604.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 24.0,
                child: GeneratedGroup63Widget5(),
              ),
              Positioned(
                left: 164.0,
                top: 604.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 24.0,
                child: GeneratedGroup64Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 46.0,
                child: GeneratedGroup66Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup21Widget8(),
              ),
              Positioned(
                left: 5.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 15.0,
                child: GeneratedYourBookingWidget2(),
              ),
              Positioned(
                left: 133.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 18.0,
                child: GeneratedPricetableWidget2(),
              ),
              Positioned(
                left: 255.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 18.0,
                child: GeneratedTotalWidget9(),
              ),
              Positioned(
                left: 336.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 18.0,
                child: GeneratedQuantityWidget9(),
              ),
              Positioned(
                left: 8.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 21.0,
                child: GeneratedTablesWidget2(),
              ),
              Positioned(
                left: 9.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 18.0,
                child: GeneratedTotaltablesWidget2(),
              ),
              Positioned(
                left: 9.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 18.0,
                child: GeneratedGrandTotalWidget25(),
              ),
              Positioned(
                left: 9.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 18.0,
                child: GeneratedOtherchargesWidget7(),
              ),
              Positioned(
                left: 332.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup47Widget67(),
              ),
              Positioned(
                left: 327.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup68Widget6(),
              ),
              Positioned(
                left: 327.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup69Widget2(),
              ),
              Positioned(
                left: 136.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup46Widget65(),
              ),
              Positioned(
                left: 338.0,
                top: 369.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup56Widget9(),
              ),
              Positioned(
                left: 338.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup58Widget12(),
              ),
              Positioned(
                left: 338.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup57Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine216Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine219Widget23(),
              ),
              Positioned(
                left: 8.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 18.0,
                child: GeneratedTableReservationWidget2(),
              ),
              Positioned(
                left: 8.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 16.0,
                child: GeneratedNoofpeopleWidget2(),
              ),
              Positioned(
                left: 8.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 16.0,
                child: GeneratedNooftablesWidget2(),
              ),
              Positioned(
                left: 8.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 12.0,
                child: Generatedmax6peoplepertableWidget4(),
              ),
              Positioned(
                left: 73.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 12.0,
                child:
                    Generated50ofthismoneycanbereclaimedwhileorderingWidget1(),
              ),
              Positioned(
                left: 243.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup48Widget35(),
              )
            ]),
      ),
    ));
  }
}
