import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus2widget1/generated/GeneratedGroup49Widget10.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus2widget1/generated/Generated12Sec9ambalaHaryana7206899009Widget5.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus2widget1/generated/GeneratedGroup53Widget4.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus2widget1/generated/GeneratedCharlesFoodHubWidget15.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus2widget1/generated/GeneratedServicesProvidedWidget7.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus2widget1/generated/GeneratedGroup48Widget19.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus2widget1/generated/GeneratedRectangle10Widget11.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus2widget1/generated/GeneratedBxbxarrowbackWidget7.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus2widget1/generated/GeneratedGroup44Widget28.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus2widget1/generated/GeneratedGroup52Widget4.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus2widget1/generated/GeneratedGroup51Widget10.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus2widget1/generated/GeneratedGroup50Widget10.dart';

/* Frame iPhone 8 Plus - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone8Plus2Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 195.0,
                child: GeneratedRectangle10Widget11(),
              ),
              Positioned(
                left: 10.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 12.0,
                child: Generated12Sec9ambalaHaryana7206899009Widget5(),
              ),
              Positioned(
                left: 2.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget7(),
              ),
              Positioned(
                left: 7.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 29.0,
                child: GeneratedCharlesFoodHubWidget15(),
              ),
              Positioned(
                left: 7.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 15.0,
                child: GeneratedServicesProvidedWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget28(),
              ),
              Positioned(
                left: 12.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup48Widget19(),
              ),
              Positioned(
                left: 12.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup49Widget10(),
              ),
              Positioned(
                left: 12.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup50Widget10(),
              ),
              Positioned(
                left: 12.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup51Widget10(),
              ),
              Positioned(
                left: 12.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup52Widget4(),
              ),
              Positioned(
                left: 12.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup53Widget4(),
              )
            ]),
      ),
    ));
  }
}
