import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedQuantityWidget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup52Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup56Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedColdCoffeeWidget19.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup59Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup50Widget17.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedVegSandwichWidget19.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedBxbxbookWidget38.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup58Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup43Widget17.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup53Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/Generated7206899009CharlesFHgmailcomWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedLine219Widget21.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup44Widget36.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedPriceItemWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedClaritynotificationlineWidget39.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup55Widget21.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedYourOrderWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup57Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedTotalWidget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGrandTotalWidget20.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedLine217Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup60Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup19Widget12.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup64Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedVegSaladWidget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedBxbxbookWidget39.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedLine218Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedLine220Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup47Widget65.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedClaritynotificationlineWidget38.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedItemTotalWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedSelectDateandTimeWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup66Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup49Widget17.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedForprebookingyouneedtobookatleastan1hourbeforethepickup2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedTaxWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup54Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedLine216Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup63Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup48Widget33.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup46Widget63.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget3/generated/GeneratedGroup51Widget17.dart';

/* Frame Pre Order
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPreOrderWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget38(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget38(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup43Widget17(),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget39(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget39(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget21(),
              ),
              Positioned(
                left: 1.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup19Widget12(),
              ),
              Positioned(
                left: 90.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 225.0,
                height: 14.0,
                child: Generated7206899009CharlesFHgmailcomWidget3(),
              ),
              Positioned(
                left: 6.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 14.0,
                child: GeneratedYourOrderWidget5(),
              ),
              Positioned(
                left: 135.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 17.0,
                child: GeneratedPriceItemWidget5(),
              ),
              Positioned(
                left: 252.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 17.0,
                child: GeneratedTotalWidget7(),
              ),
              Positioned(
                left: 337.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 17.0,
                child: GeneratedQuantityWidget7(),
              ),
              Positioned(
                left: 6.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 21.0,
                child: GeneratedVegSaladWidget7(),
              ),
              Positioned(
                left: 8.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 21.0,
                child: GeneratedVegSandwichWidget19(),
              ),
              Positioned(
                left: 8.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 18.0,
                child: GeneratedColdCoffeeWidget19(),
              ),
              Positioned(
                left: 9.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 18.0,
                child: GeneratedItemTotalWidget5(),
              ),
              Positioned(
                left: 9.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 18.0,
                child: GeneratedGrandTotalWidget20(),
              ),
              Positioned(
                left: 8.0,
                top: 342.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 18.0,
                child: GeneratedTaxWidget1(),
              ),
              Positioned(
                left: 332.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup47Widget65(),
              ),
              Positioned(
                left: 332.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup49Widget17(),
              ),
              Positioned(
                left: 332.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup52Widget7(),
              ),
              Positioned(
                left: 136.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup46Widget63(),
              ),
              Positioned(
                left: 136.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 19.0,
                child: GeneratedGroup50Widget17(),
              ),
              Positioned(
                left: 136.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup53Widget7(),
              ),
              Positioned(
                left: 243.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup48Widget33(),
              ),
              Positioned(
                left: 243.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 19.0,
                child: GeneratedGroup51Widget17(),
              ),
              Positioned(
                left: 243.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup54Widget7(),
              ),
              Positioned(
                left: 338.0,
                top: 316.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup56Widget7(),
              ),
              Positioned(
                left: 338.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup58Widget10(),
              ),
              Positioned(
                left: 338.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup57Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine216Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine217Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine218Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine219Widget21(),
              ),
              Positioned(
                left: 82.0,
                top: 416.0073547363281,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup59Widget7(),
              ),
              Positioned(
                left: 215.0,
                top: 416.0073547363281,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup60Widget7(),
              ),
              Positioned(
                left: 22.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 12.0,
                child:
                    GeneratedForprebookingyouneedtobookatleastan1hourbeforethepickup2(),
              ),
              Positioned(
                left: 207.5,
                top: 447.01470947265625,
                right: null,
                bottom: null,
                width: 34.01470184326172,
                height: 1.0,
                child: GeneratedLine220Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget36(),
              ),
              Positioned(
                left: 9.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 15.0,
                child: GeneratedSelectDateandTimeWidget3(),
              ),
              Positioned(
                left: 10.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 24.0,
                child: GeneratedGroup63Widget3(),
              ),
              Positioned(
                left: 164.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 24.0,
                child: GeneratedGroup64Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 46.0,
                child: GeneratedGroup66Widget3(),
              )
            ]),
      ),
    ));
  }
}
