import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedRectangle14Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedSignUpWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedRectangle12Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedRectangle11Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedRectangle12Widget11.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedRectangle13Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedFullName________________________Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedSIGNINWITHWidget14.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedRectangle13Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedConfirmPasswordWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedEnterPasswordWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedHaveanaccountyetSignInWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedORWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedEnterOTPWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedRectangle10Widget19.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget2/generated/GeneratedEnterEmailPhonenumberWidget5.dart';

/* Frame Info
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInfoWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 52.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 36.0,
                child: GeneratedFullName________________________Widget2(),
              ),
              Positioned(
                left: 53.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 41.0,
                child: GeneratedEnterEmailPhonenumberWidget5(),
              ),
              Positioned(
                left: 53.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 41.0,
                child: GeneratedEnterPasswordWidget5(),
              ),
              Positioned(
                left: 53.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 43.0,
                child: GeneratedConfirmPasswordWidget2(),
              ),
              Positioned(
                left: 54.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 38.0,
                child: GeneratedRectangle10Widget19(),
              ),
              Positioned(
                left: 54.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 38.0,
                child: GeneratedRectangle11Widget5(),
              ),
              Positioned(
                left: 54.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 40.0,
                child: GeneratedRectangle12Widget10(),
              ),
              Positioned(
                left: 54.0,
                top: 369.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 41.0,
                child: GeneratedEnterOTPWidget2(),
              ),
              Positioned(
                left: 54.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 38.0,
                child: GeneratedRectangle14Widget5(),
              ),
              Positioned(
                left: 135.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 45.0,
                child: GeneratedRectangle13Widget4(),
              ),
              Positioned(
                left: 153.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 43.0,
                child: GeneratedSignUpWidget2(),
              ),
              Positioned(
                left: 116.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 34.0,
                child: GeneratedSIGNINWITHWidget14(),
              ),
              Positioned(
                left: 184.0,
                top: 519.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 41.0,
                child: GeneratedORWidget5(),
              ),
              Positioned(
                left: 34.0,
                top: 649.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 72.0,
                child: GeneratedHaveanaccountyetSignInWidget2(),
              ),
              Positioned(
                left: 134.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 49.0,
                child: GeneratedRectangle12Widget11(),
              ),
              Positioned(
                left: 216.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 49.0,
                child: GeneratedRectangle13Widget5(),
              )
            ]),
      ),
    ));
  }
}
