import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedairportwidget1/generated/GeneratedGroup44Widget26.dart';
import 'package:flutterapp/nowaytapp/generatedairportwidget1/generated/GeneratedGroup3Widget11.dart';
import 'package:flutterapp/nowaytapp/generatedairportwidget1/generated/GeneratedGroup20Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedairportwidget1/generated/GeneratedGroup22Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedairportwidget1/generated/GeneratedGroup19Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedairportwidget1/generated/GeneratedFrame1Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedairportwidget1/generated/GeneratedPlacesnearyouWidget8.dart';
import 'package:flutterapp/nowaytapp/generatedairportwidget1/generated/GeneratedOrdercanbeprocessedin45minWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedairportwidget1/generated/GeneratedBxbxbookWidget34.dart';
import 'package:flutterapp/nowaytapp/generatedairportwidget1/generated/GeneratedClaritynotificationlineWidget34.dart';
import 'package:flutterapp/nowaytapp/generatedairportwidget1/generated/GeneratedGroup34Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedairportwidget1/generated/GeneratedOrdercanbeprocessedin50minWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedairportwidget1/generated/GeneratedOrdercanbeprocessedin30minWidget15.dart';
import 'package:flutterapp/nowaytapp/generatedairportwidget1/generated/GeneratedGroup43Widget14.dart';
import 'package:flutterapp/nowaytapp/generatedairportwidget1/generated/GeneratedOrdercanbeprocessedin60minWidget1.dart';

/* Frame Airport
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAirportWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(2.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 736.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 736.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(2.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(2.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 43.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 42.0,
                              child: GeneratedGroup3Widget11(),
                            ),
                            Positioned(
                              left: 5.0,
                              top: 6.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedClaritynotificationlineWidget34(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 11.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBxbxbookWidget34(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 96.0,
                              right: null,
                              bottom: null,
                              width: 407.0,
                              height: 69.0,
                              child: GeneratedFrame1Widget8(),
                            ),
                            Positioned(
                              left: 148.0,
                              top: 8.0,
                              right: null,
                              bottom: null,
                              width: 129.0,
                              height: 30.0,
                              child: GeneratedGroup43Widget14(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 86.0,
                              height: 12.0,
                              child: GeneratedPlacesnearyouWidget8(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 196.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup19Widget10(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 275.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup20Widget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 433.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup22Widget8(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 354.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup44Widget26(),
                            ),
                            Positioned(
                              left: 231.0,
                              top: 258.0,
                              right: null,
                              bottom: null,
                              width: 181.0,
                              height: 12.0,
                              child:
                                  GeneratedOrdercanbeprocessedin30minWidget15(),
                            ),
                            Positioned(
                              left: 232.0,
                              top: 335.0,
                              right: null,
                              bottom: null,
                              width: 179.0,
                              height: 12.0,
                              child:
                                  GeneratedOrdercanbeprocessedin45minWidget1(),
                            ),
                            Positioned(
                              left: 231.0,
                              top: 416.0,
                              right: null,
                              bottom: null,
                              width: 181.0,
                              height: 12.0,
                              child:
                                  GeneratedOrdercanbeprocessedin50minWidget5(),
                            ),
                            Positioned(
                              left: 231.0,
                              top: 496.0,
                              right: null,
                              bottom: null,
                              width: 181.0,
                              height: 12.0,
                              child:
                                  GeneratedOrdercanbeprocessedin60minWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 686.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 50.0,
                              child: GeneratedGroup34Widget8(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
