import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/GeneratedGroup83Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/GeneratedQRcodeisnotfunctioningWidget13.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/GeneratedGroup82Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/GeneratedGroup19Widget15.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/GeneratedGroup81Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/GeneratedRectangle458Widget13.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/GeneratedUseReferenceCodeWidget13.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/GeneratedGroup44Widget47.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/GeneratedClaritynotificationlineWidget61.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/GeneratedEstimatedTime2days4hrs30minsWidget17.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/GeneratedDateandTimeWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/GeneratedBxbxbookWidget61.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/GeneratedLine219Widget39.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/GeneratedYourReferenceQRCodeWidget13.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/GeneratedGroup55Widget39.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget13/generated/Generated232979Widget13.dart';

/* Frame After Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAfterPaymentWidget13 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget61(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget61(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget39(),
              ),
              Positioned(
                left: -0.00048828125,
                top: 57.5,
                right: null,
                bottom: null,
                width: 414.001220703125,
                height: 1.0,
                child: GeneratedLine219Widget39(),
              ),
              Positioned(
                left: 1.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup19Widget15(),
              ),
              Positioned(
                left: 103.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 19.0,
                child: GeneratedYourReferenceQRCodeWidget13(),
              ),
              Positioned(
                left: 137.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 19.0,
                child: GeneratedDateandTimeWidget5(),
              ),
              Positioned(
                left: 247.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 24.0,
                child: GeneratedGroup81Widget5(),
              ),
              Positioned(
                left: 63.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 18.0,
                child: GeneratedEstimatedTime2days4hrs30minsWidget17(),
              ),
              Positioned(
                left: 37.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 24.0,
                child: GeneratedGroup82Widget5(),
              ),
              Positioned(
                left: 111.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 193.0,
                child: GeneratedRectangle458Widget13(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget47(),
              ),
              Positioned(
                left: 110.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 41.0,
                child: GeneratedGroup83Widget5(),
              ),
              Positioned(
                left: 122.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 15.0,
                child: GeneratedQRcodeisnotfunctioningWidget13(),
              ),
              Positioned(
                left: 117.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 19.0,
                child: GeneratedUseReferenceCodeWidget13(),
              ),
              Positioned(
                left: 176.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 22.0,
                child: Generated232979Widget13(),
              )
            ]),
      ),
    ));
  }
}
