import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedSignUpWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedRectangle12Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedORWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedRectangle12Widget6.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedRectangle10Widget10.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedEnterPasswordWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedRectangle13Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedSIGNINWITHWidget9.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedHaveanaccountyetSignInWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedFullName________________________Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedRectangle11Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedEnterOTPWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedEnterEmailPhonenumberWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedConfirmPasswordWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedRectangle13Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedinfowidget1/generated/GeneratedRectangle14Widget3.dart';

/* Frame Info
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInfoWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 52.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 36.0,
                child: GeneratedFullName________________________Widget1(),
              ),
              Positioned(
                left: 53.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 41.0,
                child: GeneratedEnterEmailPhonenumberWidget3(),
              ),
              Positioned(
                left: 53.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 41.0,
                child: GeneratedEnterPasswordWidget3(),
              ),
              Positioned(
                left: 53.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 43.0,
                child: GeneratedConfirmPasswordWidget1(),
              ),
              Positioned(
                left: 54.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 38.0,
                child: GeneratedRectangle10Widget10(),
              ),
              Positioned(
                left: 54.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 38.0,
                child: GeneratedRectangle11Widget3(),
              ),
              Positioned(
                left: 54.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 40.0,
                child: GeneratedRectangle12Widget6(),
              ),
              Positioned(
                left: 54.0,
                top: 369.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 41.0,
                child: GeneratedEnterOTPWidget1(),
              ),
              Positioned(
                left: 54.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 38.0,
                child: GeneratedRectangle14Widget3(),
              ),
              Positioned(
                left: 135.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 45.0,
                child: GeneratedRectangle13Widget2(),
              ),
              Positioned(
                left: 153.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 43.0,
                child: GeneratedSignUpWidget1(),
              ),
              Positioned(
                left: 116.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 34.0,
                child: GeneratedSIGNINWITHWidget9(),
              ),
              Positioned(
                left: 184.0,
                top: 519.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 41.0,
                child: GeneratedORWidget3(),
              ),
              Positioned(
                left: 34.0,
                top: 649.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 72.0,
                child: GeneratedHaveanaccountyetSignInWidget1(),
              ),
              Positioned(
                left: 134.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 49.0,
                child: GeneratedRectangle12Widget7(),
              ),
              Positioned(
                left: 216.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 49.0,
                child: GeneratedRectangle13Widget3(),
              )
            ]),
      ),
    ));
  }
}
