import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget1/generated/GeneratedGroup54Widget5.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget1/generated/GeneratedGroup51Widget15.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget1/generated/GeneratedRectangle10Widget17.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget1/generated/GeneratedCoffeeStallWidget14.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget1/generated/GeneratedServicesProvidedWidget13.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget1/generated/GeneratedGroup50Widget15.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget1/generated/GeneratedShop72ChandigarhInternationalAirportMohaliWidget16.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget1/generated/GeneratedGroup48Widget29.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget1/generated/GeneratedGroup49Widget15.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget1/generated/GeneratedGroup44Widget34.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget1/generated/GeneratedBxbxarrowbackWidget13.dart';

/* Frame iPhone 8 Plus - 16
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone8Plus16Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 195.0,
                child: GeneratedRectangle10Widget17(),
              ),
              Positioned(
                left: 10.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 251.0,
                height: 12.0,
                child:
                    GeneratedShop72ChandigarhInternationalAirportMohaliWidget16(),
              ),
              Positioned(
                left: 2.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget13(),
              ),
              Positioned(
                left: 10.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 29.0,
                child: GeneratedCoffeeStallWidget14(),
              ),
              Positioned(
                left: 7.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 15.0,
                child: GeneratedServicesProvidedWidget13(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget34(),
              ),
              Positioned(
                left: 124.0,
                top: 645.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 29.0,
                child: GeneratedGroup54Widget5(),
              ),
              Positioned(
                left: 12.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup48Widget29(),
              ),
              Positioned(
                left: 12.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup49Widget15(),
              ),
              Positioned(
                left: 12.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup50Widget15(),
              ),
              Positioned(
                left: 12.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup51Widget15(),
              )
            ]),
      ),
    ));
  }
}
