import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget/generated/GeneratedBxbxbookWidget16.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget/generated/GeneratedGroup19Widget6.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget/generated/GeneratedYourQueueNois007Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget/generated/GeneratedClaritynotificationlineWidget16.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget/generated/GeneratedYourReferenceQRCodeWidget.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget/generated/GeneratedYourorderwillbereadyin24minutesWidget.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget/generated/GeneratedGroup84Widget.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget/generated/GeneratedGroup44Widget15.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget/generated/GeneratedGroup55Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget/generated/Generated232979Widget.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget/generated/GeneratedLine219Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget/generated/GeneratedRectangle458Widget.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget/generated/GeneratedUseReferenceCodeWidget.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget/generated/GeneratedQRcodeisnotfunctioningWidget.dart';

/* Frame After Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAfterPaymentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget16(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget16(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget7(),
              ),
              Positioned(
                left: -0.00048828125,
                top: 57.5,
                right: null,
                bottom: null,
                width: 414.001220703125,
                height: 1.0,
                child: GeneratedLine219Widget7(),
              ),
              Positioned(
                left: 1.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup19Widget6(),
              ),
              Positioned(
                left: 109.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 19.0,
                child: GeneratedYourQueueNois007Widget3(),
              ),
              Positioned(
                left: 100.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 19.0,
                child: GeneratedYourReferenceQRCodeWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 19.0,
                child: GeneratedYourorderwillbereadyin24minutesWidget(),
              ),
              Positioned(
                left: 109.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 193.0,
                child: GeneratedRectangle458Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget15(),
              ),
              Positioned(
                left: 110.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 41.0,
                child: GeneratedGroup84Widget(),
              ),
              Positioned(
                left: 121.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 15.0,
                child: GeneratedQRcodeisnotfunctioningWidget(),
              ),
              Positioned(
                left: 116.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 19.0,
                child: GeneratedUseReferenceCodeWidget(),
              ),
              Positioned(
                left: 175.0,
                top: 548.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 22.0,
                child: Generated232979Widget(),
              )
            ]),
      ),
    ));
  }
}
