import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget/generated/GeneratedGroup76Widget.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget/generated/GeneratedBxbxbookWidget13.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget/generated/GeneratedPaymentOptionsWidget.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget/generated/GeneratedGroup61Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget/generated/GeneratedClaritynotificationlineWidget13.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget/generated/GeneratedGroup55Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget/generated/GeneratedGroup19Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget/generated/GeneratedGroup75Widget.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget/generated/GeneratedLine219Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget/generated/GeneratedGroup79Widget.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget/generated/GeneratedYourorderwillbereadyin30minutesWidget.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget/generated/GeneratedGrandTotalWidget8.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget/generated/GeneratedYourQueueNois007Widget.dart';

/* Frame After clicking book now
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAfterclickingbooknowWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget13(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget13(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget4(),
              ),
              Positioned(
                left: -0.00048828125,
                top: 57.5,
                right: null,
                bottom: null,
                width: 414.001220703125,
                height: 1.0,
                child: GeneratedLine219Widget4(),
              ),
              Positioned(
                left: 55.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 18.0,
                child: GeneratedYourorderwillbereadyin30minutesWidget(),
              ),
              Positioned(
                left: 331.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 22.0,
                child: GeneratedGroup61Widget4(),
              ),
              Positioned(
                left: 1.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup19Widget5(),
              ),
              Positioned(
                left: 8.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 19.0,
                child: GeneratedGrandTotalWidget8(),
              ),
              Positioned(
                left: 54.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 43.0,
                child: GeneratedGroup79Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 31.0,
                child: GeneratedPaymentOptionsWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 58.0,
                child: GeneratedGroup76Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 58.0,
                child: GeneratedGroup75Widget(),
              ),
              Positioned(
                left: 106.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 19.0,
                child: GeneratedYourQueueNois007Widget(),
              )
            ]),
      ),
    ));
  }
}
