import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget/generated/GeneratedShop72ChandigarhInternationalAirportMohaliWidget5.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget/generated/GeneratedGroup44Widget10.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget/generated/GeneratedCoffeeStallWidget4.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget/generated/GeneratedGroup50Widget5.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget/generated/GeneratedRectangle10Widget8.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget/generated/GeneratedBxbxarrowbackWidget6.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget/generated/GeneratedServicesProvidedWidget6.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget/generated/GeneratedGroup48Widget10.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget/generated/GeneratedGroup54Widget1.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget/generated/GeneratedGroup49Widget5.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus16widget/generated/GeneratedGroup51Widget5.dart';

/* Frame iPhone 8 Plus - 16
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone8Plus16Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 195.0,
                child: GeneratedRectangle10Widget8(),
              ),
              Positioned(
                left: 10.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 251.0,
                height: 12.0,
                child:
                    GeneratedShop72ChandigarhInternationalAirportMohaliWidget5(),
              ),
              Positioned(
                left: 2.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget6(),
              ),
              Positioned(
                left: 10.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 29.0,
                child: GeneratedCoffeeStallWidget4(),
              ),
              Positioned(
                left: 7.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 15.0,
                child: GeneratedServicesProvidedWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget10(),
              ),
              Positioned(
                left: 124.0,
                top: 645.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 29.0,
                child: GeneratedGroup54Widget1(),
              ),
              Positioned(
                left: 12.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup48Widget10(),
              ),
              Positioned(
                left: 12.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup49Widget5(),
              ),
              Positioned(
                left: 12.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup50Widget5(),
              ),
              Positioned(
                left: 12.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup51Widget5(),
              )
            ]),
      ),
    ));
  }
}
