import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus12widget/generated/GeneratedBxbxarrowbackWidget2.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus12widget/generated/GeneratedTajRestaurantWidget3.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus12widget/generated/GeneratedGroup48Widget2.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus12widget/generated/Generatedmax6peoplepertableWidget.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus12widget/generated/GeneratedRectangle10Widget4.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus12widget/generated/GeneratedServicesProvidedWidget2.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus12widget/generated/GeneratedGroup44Widget6.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus12widget/generated/Generated12Sec9ambalaHaryana7206899009Widget1.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus12widget/generated/GeneratedGroup86Widget.dart';

/* Frame iPhone 8 Plus - 12
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone8Plus12Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 195.0,
                child: GeneratedRectangle10Widget4(),
              ),
              Positioned(
                left: 10.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 12.0,
                child: Generated12Sec9ambalaHaryana7206899009Widget1(),
              ),
              Positioned(
                left: 2.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget2(),
              ),
              Positioned(
                left: 12.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 29.0,
                child: GeneratedTajRestaurantWidget3(),
              ),
              Positioned(
                left: 7.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 15.0,
                child: GeneratedServicesProvidedWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget6(),
              ),
              Positioned(
                left: 12.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup48Widget2(),
              ),
              Positioned(
                left: 87.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 13.0,
                child: Generatedmax6peoplepertableWidget(),
              ),
              Positioned(
                left: 114.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 41.0,
                child: GeneratedGroup86Widget(),
              )
            ]),
      ),
    ));
  }
}
