import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedForgotthepasswordWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedRectangle11Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedSIGNINWITHWidget13.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedSIGNINWITHWidget12.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedRectangle8Widget43.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedRectangle7Widget256.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedDonthaveanaccountyetSignUpWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedRectangle1Widget16.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedRectangle10Widget18.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedSIGNINWITHWidget10.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedORWidget4.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedRectangle6Widget82.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedSIGNINWITHWidget11.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedRectangle5Widget82.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedEnterEmailPhonenumberWidget4.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedSIGNINWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedEnterPasswordWidget4.dart';
import 'package:flutterapp/nowaytapp/generatedfirsttimewidget2/generated/GeneratedRectangle9Widget2.dart';

/* Frame First Time
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFirstTimeWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 84.0,
                top: -19.0,
                right: null,
                bottom: null,
                width: 245.0,
                height: 252.0,
                child: GeneratedRectangle1Widget16(),
              ),
              Positioned(
                left: 70.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 38.0,
                child: GeneratedEnterEmailPhonenumberWidget4(),
              ),
              Positioned(
                left: 131.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 38.0,
                child: GeneratedEnterPasswordWidget4(),
              ),
              Positioned(
                left: 74.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 38.0,
                child: GeneratedRectangle5Widget82(),
              ),
              Positioned(
                left: 74.0,
                top: 356.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 38.0,
                child: GeneratedRectangle6Widget82(),
              ),
              Positioned(
                left: 133.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 21.0,
                child: GeneratedForgotthepasswordWidget2(),
              ),
              Positioned(
                left: 140.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 35.0,
                child: GeneratedRectangle7Widget256(),
              ),
              Positioned(
                left: 211.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 34.0,
                child: GeneratedRectangle8Widget43(),
              ),
              Positioned(
                left: 119.0,
                top: 553.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 34.0,
                child: GeneratedSIGNINWITHWidget10(),
              ),
              Positioned(
                left: 119.0,
                top: 553.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 34.0,
                child: GeneratedSIGNINWITHWidget11(),
              ),
              Positioned(
                left: 119.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 34.0,
                child: GeneratedSIGNINWITHWidget12(),
              ),
              Positioned(
                left: 119.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 34.0,
                child: GeneratedSIGNINWITHWidget13(),
              ),
              Positioned(
                left: 187.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 41.0,
                child: GeneratedORWidget4(),
              ),
              Positioned(
                left: 37.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 72.0,
                child: GeneratedDonthaveanaccountyetSignUpWidget2(),
              ),
              Positioned(
                left: 141.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 43.0,
                child: GeneratedRectangle9Widget2(),
              ),
              Positioned(
                left: 156.0,
                top: 458.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 34.0,
                child: GeneratedSIGNINWidget2(),
              ),
              Positioned(
                left: 143.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 49.0,
                child: GeneratedRectangle10Widget18(),
              ),
              Positioned(
                left: 222.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 49.0,
                child: GeneratedRectangle11Widget4(),
              )
            ]),
      ),
    ));
  }
}
