import 'package:flutter/material.dart';

/* Frame iPhone 8 Plus - 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone8Plus11Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 416.0,
        height: 741.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 255, 255, 255),
          ),
        ),
      ),
    ));
  }
}
