import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup19Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedSardhadiagnosticWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup43Widget11.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup40Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedRectangle5Widget48.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedRectangle5Widget50.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup12Widget31.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup3Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedEarliestavailablein2hrsWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup20Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedRectangle6Widget50.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedFuturediagnosticWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup13Widget30.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedBxbxbookWidget31.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup15Widget18.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedPlot72Sec9ambalaHaryanaWidget4.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup21Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedEarliestavailablein30minWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup39Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedPlacesnearyouWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedOrdercanbeprocessedin30minWidget8.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedFrame1Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedPlot22Sec9ambalaHaryanaWidget4.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup38Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup35Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedClaritynotificationlineWidget31.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedRectangle6Widget48.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup22Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup16Widget21.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup14Widget29.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup34Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup37Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup14Widget31.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup12Widget29.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup13Widget32.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup36Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedhomewidget27/generated/GeneratedGroup16Widget23.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget27 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(2.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1142.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 736.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(2.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(2.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 43.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 42.0,
                              child: GeneratedGroup3Widget8(),
                            ),
                            Positioned(
                              left: 5.0,
                              top: 6.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedClaritynotificationlineWidget31(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 11.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBxbxbookWidget31(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 96.0,
                              right: null,
                              bottom: null,
                              width: 407.0,
                              height: 69.0,
                              child: GeneratedFrame1Widget5(),
                            ),
                            Positioned(
                              left: 148.0,
                              top: 8.0,
                              right: null,
                              bottom: null,
                              width: 129.0,
                              height: 30.0,
                              child: GeneratedGroup43Widget11(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 86.0,
                              height: 12.0,
                              child: GeneratedPlacesnearyouWidget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 195.0,
                              right: null,
                              bottom: null,
                              width: 416.0,
                              height: 80.0,
                              child: GeneratedRectangle5Widget48(),
                            ),
                            Positioned(
                              left: 228.0,
                              top: 256.0,
                              right: null,
                              bottom: null,
                              width: 181.0,
                              height: 12.0,
                              child:
                                  GeneratedOrdercanbeprocessedin30minWidget8(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 203.0,
                              right: null,
                              bottom: null,
                              width: 99.0,
                              height: 13.0,
                              child: GeneratedSardhadiagnosticWidget5(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 218.0,
                              right: null,
                              bottom: null,
                              width: 132.0,
                              height: 11.0,
                              child: GeneratedPlot72Sec9ambalaHaryanaWidget4(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 202.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 64.0,
                              child: GeneratedRectangle6Widget48(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 232.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 15.0,
                              child: GeneratedGroup12Widget29(),
                            ),
                            Positioned(
                              left: 144.0,
                              top: 232.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 15.0,
                              child: GeneratedGroup13Widget30(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 232.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 15.0,
                              child: GeneratedGroup14Widget29(),
                            ),
                            Positioned(
                              left: 247.0,
                              top: 232.0,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 15.0,
                              child: GeneratedGroup15Widget18(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 250.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 15.0,
                              child: GeneratedGroup16Widget21(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 669.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup35Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 274.0,
                              right: null,
                              bottom: null,
                              width: 416.0,
                              height: 80.0,
                              child: GeneratedRectangle5Widget50(),
                            ),
                            Positioned(
                              left: 275.0,
                              top: 334.0,
                              right: null,
                              bottom: null,
                              width: 132.0,
                              height: 12.0,
                              child: GeneratedEarliestavailablein2hrsWidget2(),
                            ),
                            Positioned(
                              left: 91.0,
                              top: 282.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 13.0,
                              child: GeneratedFuturediagnosticWidget3(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 297.0,
                              right: null,
                              bottom: null,
                              width: 133.0,
                              height: 11.0,
                              child: GeneratedPlot22Sec9ambalaHaryanaWidget4(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 281.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 64.0,
                              child: GeneratedRectangle6Widget50(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 311.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 15.0,
                              child: GeneratedGroup12Widget31(),
                            ),
                            Positioned(
                              left: 144.0,
                              top: 311.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 15.0,
                              child: GeneratedGroup13Widget32(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 311.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 15.0,
                              child: GeneratedGroup14Widget31(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 329.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 15.0,
                              child: GeneratedGroup16Widget23(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 748.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup36Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 353.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup19Widget8(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 827.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup37Widget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 432.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup20Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 906.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup38Widget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 511.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup21Widget7(),
                            ),
                            Positioned(
                              left: 258.0,
                              top: 572.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 12.0,
                              child: GeneratedEarliestavailablein30minWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 985.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup39Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 590.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup22Widget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1064.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup40Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 686.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 50.0,
                              child: GeneratedGroup34Widget5(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
