import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup57Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedLine217Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedClaritynotificationlineWidget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedBxbxbookWidget8.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedItemTotalWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedYourOrderWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup19Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup66Widget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup51Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedLine219Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedBxbxbookWidget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup47Widget30.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedLine220Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedQuantityWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup50Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup60Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup56Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup55Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedTotalWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup44Widget12.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup48Widget14.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedLine218Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup43Widget6.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup59Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup52Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedVegSandwichWidget9.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedPriceItemWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup58Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedClaritynotificationlineWidget8.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedForprebookingyouneedtobookatleastan1hourbeforethepickup.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup53Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedSelectDateandTimeWidget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedVegSaladWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup63Widget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup49Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup64Widget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup46Widget29.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGroup54Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedGrandTotalWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/Generated7206899009CharlesFHgmailcomWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedTaxWidget.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedLine216Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget/generated/GeneratedColdCoffeeWidget9.dart';

/* Frame Pre Order
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPreOrderWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget7(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget7(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup43Widget6(),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget8(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget8(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget1(),
              ),
              Positioned(
                left: 1.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup19Widget4(),
              ),
              Positioned(
                left: 90.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 225.0,
                height: 14.0,
                child: Generated7206899009CharlesFHgmailcomWidget1(),
              ),
              Positioned(
                left: 6.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 14.0,
                child: GeneratedYourOrderWidget1(),
              ),
              Positioned(
                left: 135.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 17.0,
                child: GeneratedPriceItemWidget1(),
              ),
              Positioned(
                left: 252.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 17.0,
                child: GeneratedTotalWidget1(),
              ),
              Positioned(
                left: 337.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 17.0,
                child: GeneratedQuantityWidget1(),
              ),
              Positioned(
                left: 6.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 21.0,
                child: GeneratedVegSaladWidget3(),
              ),
              Positioned(
                left: 8.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 21.0,
                child: GeneratedVegSandwichWidget9(),
              ),
              Positioned(
                left: 8.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 18.0,
                child: GeneratedColdCoffeeWidget9(),
              ),
              Positioned(
                left: 9.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 18.0,
                child: GeneratedItemTotalWidget1(),
              ),
              Positioned(
                left: 9.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 18.0,
                child: GeneratedGrandTotalWidget2(),
              ),
              Positioned(
                left: 8.0,
                top: 342.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 18.0,
                child: GeneratedTaxWidget(),
              ),
              Positioned(
                left: 332.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup47Widget30(),
              ),
              Positioned(
                left: 332.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup49Widget7(),
              ),
              Positioned(
                left: 332.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup52Widget3(),
              ),
              Positioned(
                left: 136.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup46Widget29(),
              ),
              Positioned(
                left: 136.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 19.0,
                child: GeneratedGroup50Widget7(),
              ),
              Positioned(
                left: 136.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup53Widget3(),
              ),
              Positioned(
                left: 243.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup48Widget14(),
              ),
              Positioned(
                left: 243.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 19.0,
                child: GeneratedGroup51Widget7(),
              ),
              Positioned(
                left: 243.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup54Widget3(),
              ),
              Positioned(
                left: 338.0,
                top: 316.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup56Widget1(),
              ),
              Positioned(
                left: 338.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup58Widget1(),
              ),
              Positioned(
                left: 338.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup57Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine216Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine217Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine218Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine219Widget1(),
              ),
              Positioned(
                left: 82.0,
                top: 416.0073547363281,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup59Widget1(),
              ),
              Positioned(
                left: 215.0,
                top: 416.0073547363281,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup60Widget1(),
              ),
              Positioned(
                left: 22.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 12.0,
                child:
                    GeneratedForprebookingyouneedtobookatleastan1hourbeforethepickup(),
              ),
              Positioned(
                left: 207.5,
                top: 447.01470947265625,
                right: null,
                bottom: null,
                width: 34.01470184326172,
                height: 1.0,
                child: GeneratedLine220Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget12(),
              ),
              Positioned(
                left: 9.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 15.0,
                child: GeneratedSelectDateandTimeWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 24.0,
                child: GeneratedGroup63Widget(),
              ),
              Positioned(
                left: 164.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 24.0,
                child: GeneratedGroup64Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 46.0,
                child: GeneratedGroup66Widget(),
              )
            ]),
      ),
    ));
  }
}
