import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedColdCoffeeWidget8.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedLine216Widget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup57Widget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedClaritynotificationlineWidget6.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedYourOrderWidget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedClaritynotificationlineWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup49Widget6.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup47Widget29.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup19Widget3.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup48Widget13.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedVegSandwichWidget8.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/Generated7206899009CharlesFHgmailcomWidget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedYourorderwillbereadyinapproximately30minutesWidget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup60Widget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup46Widget28.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedBxbxbookWidget6.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup53Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup67Widget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedLine220Widget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedLine217Widget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedLine218Widget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup44Widget11.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedVegSaladWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup50Widget6.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup52Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedPriceItemWidget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedOtherchargesWidget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedItemTotalWidget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedLine219Widget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedTotalWidget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup43Widget5.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup58Widget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup56Widget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedIfyoubooknowWidget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedQuantityWidget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup59Widget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedBxbxbookWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGrandTotalWidget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup54Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup51Widget6.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedYourQueueNowillbe007Widget.dart';
import 'package:flutterapp/nowaytapp/generatedbooknowwidget/generated/GeneratedGroup55Widget.dart';

/* Frame Book Now
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBookNowWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget5(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget5(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup43Widget5(),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget6(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget6(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup19Widget3(),
              ),
              Positioned(
                left: 90.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 225.0,
                height: 14.0,
                child: Generated7206899009CharlesFHgmailcomWidget(),
              ),
              Positioned(
                left: 6.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 14.0,
                child: GeneratedYourOrderWidget(),
              ),
              Positioned(
                left: 135.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 17.0,
                child: GeneratedPriceItemWidget(),
              ),
              Positioned(
                left: 252.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 17.0,
                child: GeneratedTotalWidget(),
              ),
              Positioned(
                left: 337.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 17.0,
                child: GeneratedQuantityWidget(),
              ),
              Positioned(
                left: 6.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 21.0,
                child: GeneratedVegSaladWidget2(),
              ),
              Positioned(
                left: 8.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 21.0,
                child: GeneratedVegSandwichWidget8(),
              ),
              Positioned(
                left: 8.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 18.0,
                child: GeneratedColdCoffeeWidget8(),
              ),
              Positioned(
                left: 9.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 18.0,
                child: GeneratedItemTotalWidget(),
              ),
              Positioned(
                left: 9.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 18.0,
                child: GeneratedGrandTotalWidget(),
              ),
              Positioned(
                left: 9.0,
                top: 342.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 18.0,
                child: GeneratedOtherchargesWidget(),
              ),
              Positioned(
                left: 332.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup47Widget29(),
              ),
              Positioned(
                left: 332.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup49Widget6(),
              ),
              Positioned(
                left: 332.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup52Widget2(),
              ),
              Positioned(
                left: 136.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup46Widget28(),
              ),
              Positioned(
                left: 136.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 19.0,
                child: GeneratedGroup50Widget6(),
              ),
              Positioned(
                left: 136.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup53Widget2(),
              ),
              Positioned(
                left: 243.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup48Widget13(),
              ),
              Positioned(
                left: 243.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 19.0,
                child: GeneratedGroup51Widget6(),
              ),
              Positioned(
                left: 243.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup54Widget2(),
              ),
              Positioned(
                left: 338.0,
                top: 316.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup56Widget(),
              ),
              Positioned(
                left: 338.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup58Widget(),
              ),
              Positioned(
                left: 338.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup57Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine216Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine217Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine218Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine219Widget(),
              ),
              Positioned(
                left: 82.0,
                top: 416.0073547363281,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup59Widget(),
              ),
              Positioned(
                left: 215.0,
                top: 416.0073547363281,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup60Widget(),
              ),
              Positioned(
                left: 73.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 269.0,
                height: 12.0,
                child:
                    GeneratedYourorderwillbereadyinapproximately30minutesWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 19.0,
                child: GeneratedIfyoubooknowWidget(),
              ),
              Positioned(
                left: 207.5,
                top: 447.01470947265625,
                right: null,
                bottom: null,
                width: 34.01470184326172,
                height: 1.0,
                child: GeneratedLine220Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget11(),
              ),
              Positioned(
                left: 0.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 46.0,
                child: GeneratedGroup67Widget(),
              ),
              Positioned(
                left: 100.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 18.0,
                child: GeneratedYourQueueNowillbe007Widget(),
              )
            ]),
      ),
    ));
  }
}
