import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget2/generated/GeneratedGroup55Widget6.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget2/generated/GeneratedLine219Widget6.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget2/generated/GeneratedPaymentOptionsWidget2.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget2/generated/GeneratedGrandTotalWidget10.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget2/generated/GeneratedGroup79Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget2/generated/GeneratedGroup75Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget2/generated/GeneratedBxbxbookWidget15.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget2/generated/GeneratedClaritynotificationlineWidget15.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget2/generated/GeneratedYourreservationwillbeavailablein50minutesWidget.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget2/generated/GeneratedYourQueueNois007Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget2/generated/GeneratedGroup76Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget2/generated/GeneratedGroup21Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedafterclickingbooknowwidget2/generated/GeneratedGroup61Widget6.dart';

/* Frame After clicking book now
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAfterclickingbooknowWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget15(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget15(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget6(),
              ),
              Positioned(
                left: -0.00048828125,
                top: 57.5,
                right: null,
                bottom: null,
                width: 414.001220703125,
                height: 1.0,
                child: GeneratedLine219Widget6(),
              ),
              Positioned(
                left: 21.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 18.0,
                child:
                    GeneratedYourreservationwillbeavailablein50minutesWidget(),
              ),
              Positioned(
                left: 331.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 22.0,
                child: GeneratedGroup61Widget6(),
              ),
              Positioned(
                left: 8.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 19.0,
                child: GeneratedGrandTotalWidget10(),
              ),
              Positioned(
                left: 54.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 43.0,
                child: GeneratedGroup79Widget2(),
              ),
              Positioned(
                left: 6.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 31.0,
                child: GeneratedPaymentOptionsWidget2(),
              ),
              Positioned(
                left: 42.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 58.0,
                child: GeneratedGroup76Widget2(),
              ),
              Positioned(
                left: 42.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 58.0,
                child: GeneratedGroup75Widget2(),
              ),
              Positioned(
                left: 106.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 19.0,
                child: GeneratedYourQueueNois007Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup21Widget2(),
              )
            ]),
      ),
    ));
  }
}
