import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedfoodwidget/generated/GeneratedFrame1Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedfoodwidget/generated/GeneratedGroup34Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedfoodwidget/generated/GeneratedGroup44Widget.dart';
import 'package:flutterapp/nowaytapp/generatedfoodwidget/generated/GeneratedClaritynotificationlineWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedfoodwidget/generated/GeneratedPlacesnearyouWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedfoodwidget/generated/GeneratedGroup37Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedfoodwidget/generated/GeneratedGroup45Widget.dart';
import 'package:flutterapp/nowaytapp/generatedfoodwidget/generated/GeneratedBxbxbookWidget1.dart';
import 'package:flutterapp/nowaytapp/generatedfoodwidget/generated/GeneratedOrdercanbeprocessedin30minWidget6.dart';
import 'package:flutterapp/nowaytapp/generatedfoodwidget/generated/GeneratedGroup19Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedfoodwidget/generated/GeneratedGroup43Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedfoodwidget/generated/GeneratedGroup3Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedfoodwidget/generated/GeneratedGroup38Widget1.dart';
import 'package:flutterapp/nowaytapp/generatedfoodwidget/generated/GeneratedGroup20Widget1.dart';

/* Frame Food
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFoodWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(2.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 736.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 736.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(2.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(2.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 43.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 42.0,
                              child: GeneratedGroup3Widget2(),
                            ),
                            Positioned(
                              left: 5.0,
                              top: 6.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedClaritynotificationlineWidget1(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 11.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBxbxbookWidget1(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 96.0,
                              right: null,
                              bottom: null,
                              width: 407.0,
                              height: 69.0,
                              child: GeneratedFrame1Widget1(),
                            ),
                            Positioned(
                              left: 148.0,
                              top: 8.0,
                              right: null,
                              bottom: null,
                              width: 129.0,
                              height: 30.0,
                              child: GeneratedGroup43Widget1(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 86.0,
                              height: 12.0,
                              child: GeneratedPlacesnearyouWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 195.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup19Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 352.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup37Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 509.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup44Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 274.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup20Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 431.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup38Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 588.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 78.0,
                              child: GeneratedGroup45Widget(),
                            ),
                            Positioned(
                              left: 227.0,
                              top: 648.0,
                              right: null,
                              bottom: null,
                              width: 181.0,
                              height: 12.0,
                              child:
                                  GeneratedOrdercanbeprocessedin30minWidget6(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 686.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 50.0,
                              child: GeneratedGroup34Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
