import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedGroup83Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedRectangle458Widget6.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedClaritynotificationlineWidget26.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedGroup55Widget15.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedGroup44Widget23.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedUseReferenceCodeWidget6.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedBxbxbookWidget26.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/Generated232979Widget6.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedGroup82Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedGroup21Widget6.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedYourReferenceQRCodeWidget6.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedGroup81Widget2.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedEstimatedTime2days4hrs30minsWidget5.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedLine219Widget15.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedYourreservationwillbeexpireafter10minutesfromdesignated1.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedQRcodeisnotfunctioningWidget6.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget6/generated/GeneratedDateandTimeWidget2.dart';

/* Frame After Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAfterPaymentWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget26(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget26(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget15(),
              ),
              Positioned(
                left: -0.00048828125,
                top: 57.5,
                right: null,
                bottom: null,
                width: 414.001220703125,
                height: 1.0,
                child: GeneratedLine219Widget15(),
              ),
              Positioned(
                left: 103.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 19.0,
                child: GeneratedYourReferenceQRCodeWidget6(),
              ),
              Positioned(
                left: 137.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 19.0,
                child: GeneratedDateandTimeWidget2(),
              ),
              Positioned(
                left: 247.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 24.0,
                child: GeneratedGroup81Widget2(),
              ),
              Positioned(
                left: 63.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 18.0,
                child: GeneratedEstimatedTime2days4hrs30minsWidget5(),
              ),
              Positioned(
                left: 37.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 24.0,
                child: GeneratedGroup82Widget2(),
              ),
              Positioned(
                left: 111.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 193.0,
                child: GeneratedRectangle458Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget23(),
              ),
              Positioned(
                left: 110.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 41.0,
                child: GeneratedGroup83Widget2(),
              ),
              Positioned(
                left: 122.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 15.0,
                child: GeneratedQRcodeisnotfunctioningWidget6(),
              ),
              Positioned(
                left: 117.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 19.0,
                child: GeneratedUseReferenceCodeWidget6(),
              ),
              Positioned(
                left: 176.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 22.0,
                child: Generated232979Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup21Widget6(),
              ),
              Positioned(
                left: 30.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 12.0,
                child:
                    GeneratedYourreservationwillbeexpireafter10minutesfromdesignated1(),
              )
            ]),
      ),
    ));
  }
}
