import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/GeneratedLine219Widget13.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/GeneratedGroup19Widget7.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/GeneratedClaritynotificationlineWidget24.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/GeneratedGroup55Widget13.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/Generated232979Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/GeneratedDateandTimeWidget.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/GeneratedRectangle458Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/GeneratedGroup44Widget21.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/GeneratedGroup83Widget.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/GeneratedYourReferenceQRCodeWidget4.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/GeneratedGroup81Widget.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/GeneratedUseReferenceCodeWidget4.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/GeneratedGroup82Widget.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/GeneratedEstimatedTime2days4hrs30minsWidget3.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/GeneratedQRcodeisnotfunctioningWidget4.dart';
import 'package:flutterapp/nowaytapp/generatedafterpaymentwidget4/generated/GeneratedBxbxbookWidget24.dart';

/* Frame After Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAfterPaymentWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget24(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget24(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget13(),
              ),
              Positioned(
                left: -0.00048828125,
                top: 57.5,
                right: null,
                bottom: null,
                width: 414.001220703125,
                height: 1.0,
                child: GeneratedLine219Widget13(),
              ),
              Positioned(
                left: 1.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup19Widget7(),
              ),
              Positioned(
                left: 103.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 19.0,
                child: GeneratedYourReferenceQRCodeWidget4(),
              ),
              Positioned(
                left: 137.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 19.0,
                child: GeneratedDateandTimeWidget(),
              ),
              Positioned(
                left: 247.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 24.0,
                child: GeneratedGroup81Widget(),
              ),
              Positioned(
                left: 63.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 18.0,
                child: GeneratedEstimatedTime2days4hrs30minsWidget3(),
              ),
              Positioned(
                left: 37.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 24.0,
                child: GeneratedGroup82Widget(),
              ),
              Positioned(
                left: 111.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 193.0,
                child: GeneratedRectangle458Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget21(),
              ),
              Positioned(
                left: 110.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 41.0,
                child: GeneratedGroup83Widget(),
              ),
              Positioned(
                left: 122.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 15.0,
                child: GeneratedQRcodeisnotfunctioningWidget4(),
              ),
              Positioned(
                left: 117.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 19.0,
                child: GeneratedUseReferenceCodeWidget4(),
              ),
              Positioned(
                left: 176.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 22.0,
                child: Generated232979Widget4(),
              )
            ]),
      ),
    ));
  }
}
