import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus15widget/generated/GeneratedServicesProvidedWidget1.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus15widget/generated/GeneratedShop72ChandigarhInternationalAirportMohaliWidget4.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus15widget/generated/GeneratedGroup48Widget1.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus15widget/generated/GeneratedGroup50Widget1.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus15widget/generated/GeneratedRectangle10Widget3.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus15widget/generated/GeneratedBxbxarrowbackWidget1.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus15widget/generated/GeneratedGroup51Widget1.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus15widget/generated/GeneratedGroup49Widget1.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus15widget/generated/GeneratedGroup44Widget5.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus15widget/generated/GeneratedCoffeeStallWidget3.dart';

/* Frame iPhone 8 Plus - 15
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone8Plus15Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 195.0,
                child: GeneratedRectangle10Widget3(),
              ),
              Positioned(
                left: 10.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 251.0,
                height: 12.0,
                child:
                    GeneratedShop72ChandigarhInternationalAirportMohaliWidget4(),
              ),
              Positioned(
                left: 2.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget1(),
              ),
              Positioned(
                left: 10.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 29.0,
                child: GeneratedCoffeeStallWidget3(),
              ),
              Positioned(
                left: 7.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 15.0,
                child: GeneratedServicesProvidedWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget5(),
              ),
              Positioned(
                left: 12.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup48Widget1(),
              ),
              Positioned(
                left: 12.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup49Widget1(),
              ),
              Positioned(
                left: 12.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup50Widget1(),
              ),
              Positioned(
                left: 12.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 53.0,
                child: GeneratedGroup51Widget1(),
              )
            ]),
      ),
    ));
  }
}
