import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedTotalWidget8.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup43Widget18.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedForprebookingyouneedtobookatleastan1hourbeforethepickup3.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedClaritynotificationlineWidget41.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedLine216Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup47Widget66.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup44Widget37.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedBiscuitsPacketWidget6.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup63Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedBxbxbookWidget41.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup55Widget22.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedBxbxbookWidget40.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedLine217Widget6.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup59Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedClaritynotificationlineWidget40.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedLine220Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup57Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedQuantityWidget8.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup46Widget64.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup50Widget18.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup49Widget18.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedPriceItemWidget6.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup60Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGrandTotalWidget23.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup51Widget18.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup66Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedOtherchargesWidget6.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup64Widget4.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedSelectDateandTimeWidget4.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup22Widget9.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedYourOrderWidget6.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedItemTotalWidget6.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedLine219Widget22.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup56Widget8.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedCoffeeWidget30.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup58Widget11.dart';
import 'package:flutterapp/nowaytapp/generatedpreorderwidget4/generated/GeneratedGroup48Widget34.dart';

/* Frame Pre Order
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPreOrderWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget40(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget40(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup43Widget18(),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget41(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget41(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget22(),
              ),
              Positioned(
                left: 6.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 14.0,
                child: GeneratedYourOrderWidget6(),
              ),
              Positioned(
                left: 135.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 17.0,
                child: GeneratedPriceItemWidget6(),
              ),
              Positioned(
                left: 252.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 17.0,
                child: GeneratedTotalWidget8(),
              ),
              Positioned(
                left: 337.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 17.0,
                child: GeneratedQuantityWidget8(),
              ),
              Positioned(
                left: 82.0,
                top: 375.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup59Widget8(),
              ),
              Positioned(
                left: 215.0,
                top: 375.00732421875,
                right: null,
                bottom: null,
                width: 117.0,
                height: 30.0,
                child: GeneratedGroup60Widget8(),
              ),
              Positioned(
                left: 22.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 12.0,
                child:
                    GeneratedForprebookingyouneedtobookatleastan1hourbeforethepickup3(),
              ),
              Positioned(
                left: 207.5,
                top: 406.01470947265625,
                right: null,
                bottom: null,
                width: 34.01470184326172,
                height: 1.0,
                child: GeneratedLine220Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 50.0,
                child: GeneratedGroup44Widget37(),
              ),
              Positioned(
                left: 9.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 15.0,
                child: GeneratedSelectDateandTimeWidget4(),
              ),
              Positioned(
                left: 10.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 24.0,
                child: GeneratedGroup63Widget4(),
              ),
              Positioned(
                left: 164.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 24.0,
                child: GeneratedGroup64Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 46.0,
                child: GeneratedGroup66Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 78.0,
                child: GeneratedGroup22Widget9(),
              ),
              Positioned(
                left: 7.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 21.0,
                child: GeneratedCoffeeWidget30(),
              ),
              Positioned(
                left: 7.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 18.0,
                child: GeneratedBiscuitsPacketWidget6(),
              ),
              Positioned(
                left: 9.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 18.0,
                child: GeneratedItemTotalWidget6(),
              ),
              Positioned(
                left: 9.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 18.0,
                child: GeneratedGrandTotalWidget23(),
              ),
              Positioned(
                left: 9.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 18.0,
                child: GeneratedOtherchargesWidget6(),
              ),
              Positioned(
                left: 332.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup47Widget66(),
              ),
              Positioned(
                left: 332.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 30.0,
                child: GeneratedGroup49Widget18(),
              ),
              Positioned(
                left: 136.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup46Widget64(),
              ),
              Positioned(
                left: 136.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 19.0,
                child: GeneratedGroup50Widget18(),
              ),
              Positioned(
                left: 243.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup48Widget34(),
              ),
              Positioned(
                left: 243.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedGroup51Widget18(),
              ),
              Positioned(
                left: 338.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 19.0,
                child: GeneratedGroup56Widget8(),
              ),
              Positioned(
                left: 338.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup58Widget11(),
              ),
              Positioned(
                left: 338.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 19.0,
                child: GeneratedGroup57Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine216Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine217Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 414.9999694824219,
                height: 1.0,
                child: GeneratedLine219Widget22(),
              )
            ]),
      ),
    ));
  }
}
