import 'package:flutter/material.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget1/generated/GeneratedGroup74Widget1.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget1/generated/GeneratedClaritynotificationlineWidget60.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget1/generated/GeneratedGroup76Widget7.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget1/generated/GeneratedGroup77Widget1.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget1/generated/GeneratedGroup75Widget7.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget1/generated/GeneratedPaymentOptionsWidget13.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget1/generated/GeneratedGroup55Widget38.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget1/generated/GeneratedLine219Widget38.dart';
import 'package:flutterapp/nowaytapp/generatediphone8plus14widget1/generated/GeneratedBxbxbookWidget60.dart';

/* Frame iPhone 8 Plus - 14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone8Plus14Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 5.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedClaritynotificationlineWidget60(),
              ),
              Positioned(
                left: 382.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxbookWidget60(),
              ),
              Positioned(
                left: 148.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedGroup55Widget38(),
              ),
              Positioned(
                left: -0.00048828125,
                top: 57.5,
                right: null,
                bottom: null,
                width: 414.001220703125,
                height: 1.0,
                child: GeneratedLine219Widget38(),
              ),
              Positioned(
                left: 116.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 31.0,
                child: GeneratedPaymentOptionsWidget13(),
              ),
              Positioned(
                left: 42.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 71.0,
                child: GeneratedGroup76Widget7(),
              ),
              Positioned(
                left: 42.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 71.0,
                child: GeneratedGroup75Widget7(),
              ),
              Positioned(
                left: 42.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 71.0,
                child: GeneratedGroup74Widget1(),
              ),
              Positioned(
                left: 42.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 71.0,
                child: GeneratedGroup77Widget1(),
              )
            ]),
      ),
    ));
  }
}
